src/components/modals/qr/qr.tsx
Fixes #
-  qr scanner vibration
=> fix: qr scanner vibration

ios/haqq.xcodeproj/project.pbxproj, src/components/web3-browser/web3-browser.tsx, src/helpers/web3-browser-utils.ts, src/screens/settings-test.tsx, src/services/version.ts
Fixes #
- web3 browser useragent
=> feat: web3 browser useragent

.watchmanconfig, metro.config.js
Fixes #
Previously app had a bug with `watchman` and `metro bundler`.
`watchman` sended `Recrawled this watch 47 times, most recently because:
MustScanSubDirs UserDroppedTo resolve, please review the information on
https://facebook.github.io/watchman/docs/troubleshooting.html#recrawl`
And `metro bundler` provoked "file freeze" behavior. 
-
-
-
=> fix: metro and watchman config

.watchmanconfig
Fixes #
- removed `.watchmanconfig` to solve this problem with Watchman.
```bash
Error: A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1695275631: opendir(/Users/igroza/dev/projects/@haqq/haqq-wallet/node_modules/escape-string-regexp) -> Too many open files
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-opendir
at ChildProcess.<anonymous> (/Users/igroza/dev/projects/@haqq/haqq-wallet/node_modules/fb-watchman/index.js:212:21)
at ChildProcess.emit (node:events:513:28)
at maybeClose (node:internal/child_process:1100:16)
at Process.ChildProcess._handle.onexit …
```
=> refactor: remove .watchmanconfig

src/components/browser-edit-bookmarks.tsx, src/hooks/use-remote-config.ts, src/screens/HomeStack/BrowserStack/browser-home-page-screen.tsx, src/services/remote-config/remote-config-default-values.ts, src/services/remote-config/remote-config-service.ts, src/services/remote-config/remote-config-types.ts
Fixes #
HQM-284
- fetch web3 browser bookmark from remote config
variable name: `web3_browser_bookmarks`
```TS
Array<{
url: string;
title: string;
icon?: string;
}>
```
=> feat: fetch web3 browser bookmark from remote config

src/event-actions/on-staking-sync.ts, src/event-actions/on-wallets-staking-balance-check.ts, src/helpers/staking.ts, src/hooks/use-staking-reward.ts, src/models/index.ts, src/models/staking-metadata.ts, src/screens/HomeStack/HomeEarnStack/home-earn.tsx, src/screens/HomeStack/HomeEarnStack/home-staking.tsx, src/screens/HomeStack/HomeEarnStack/staking-info.tsx, src/screens/HomeStack/HomeEarnStack/staking-validators.tsx, src/screens/HomeStack/StakingUndelegateStack/staking-undelegate-form.tsx
- Move from realm to mobx
- Store metadata in object instead of array for faster write/read
=> refactor: Move StakingMetadata from realm to mobx

src/components/transaction-address.tsx
Address input height calculated incorrect when user uses native paste option instead of button
Fixes #
-
-
-
=> fix: Address input height

src/widgets/ad-widget/index.tsx, src/widgets/banner-widget/index.tsx
=> fix: Hide close button on banners when close event equals none

src/helpers/get-remote-balance-value.tsx, src/services/cosmos.ts, src/services/eth-network.ts, src/services/remote-config/remote-config-default-values.ts, src/services/remote-config/remote-config-types.ts
Fixes #
- [HQM-326](https://linear.app/haqq/issue/HQM-326/use-commission-multipliers-from-remote-config)
=> feat(HAM-326): Add support for remote commission multipliers setup

ios/Podfile.lock, ios/haqq.xcodeproj/project.pbxproj, package.json, yarn.lock
Fixes #
- update react-native-webview from version 13.6.0 to 13.8.1
=> chore: update react-native-webview from version 13.6.0 to 13.8.1

src/components/transaction-address.tsx
Fixes #
- fix  transaction address input
=> fix: transaction address input

src/screens/HomeStack/TransactionStack/transaction-confirmation.tsx, src/screens/HomeStack/TransactionStack/transaction-ledger.tsx, src/services/eth-network.ts
Fixes #
- fix transaction ENS issue
=> fix: transaction ENS issue

index.js, src/components/modals/view-error-details.tsx, src/components/ui/error-text.tsx, src/hooks/use-error.ts, src/i18n.ts, src/screens/HomeStack/SettingsStack/settings-test.tsx, src/services/logger.ts, src/types.ts
Fixes #
- HQM-363 sentry errors
=> feat(HQM-363): sentry errors

src/services/wallet-connect.ts
Fixes #
- HQM-370: do not show WalletConnect toasts if wc connection is not established
=> fix(HQM-370): do not show WalletConnect toasts if wc connection is not established

index.js, src/services/logger.ts
Fixes #
- sentry ScreenShoot only for fatal events
=> feat: sentry screenshoot only for fatal events

src/components/nft-viewer/nft-viewer-item-preview-large.tsx, src/components/nft-viewer/nft-viewer-item-preview-medium.tsx, src/models/nft/nft-store.ts, src/models/nft/nft-types.ts, src/screens/HomeStack/NftStack/components/nft-item-details/components/nft-item-details-attributes.tsx, src/screens/HomeStack/NftStack/components/nft-item-details/components/nft-item-details-price.tsx, src/widgets/nft-widget/components/nft-collection-view.tsx
=> fix: Hide price component if no price

src/helpers/ethereum-message-checker.ts
Fixes #
- EthereumMessageChecker allow spaces
=> fix: EthereumMessageChecker allow spaces

package.json, scripts/adb-enter-pin.sh
Fixes #
- Added a shell script `adb-enter-pin.sh` to send a 6-digit PIN code as keyboard input to all connected ADB devices.
- Added support for `-h` and `--help` options in the shell script to display usage information.
- Updated package.json to include a new script `yarn pin <6-DIGIT-PIN>` to run the shell script with Yarn.
https://github.com/haqq-network/haqq-wallet/assets/25716589/59a065b6-a5ec-4823-af73-eff317813848
=> feat: adb script for input pin

src/components/json-rpc-transaction-info.tsx, src/event-actions/on-wallet-connect-sign-transaction.ts, src/screens/HomeStack/TransactionStack/fee-settings.tsx, src/services/eth-network/eth-network.ts, src/services/json-rpc-middleware/json-rpc-methods-handlers.ts, src/services/provider-sss-initialize.ts, src/services/provider-sss.ts, src/services/push-notifications.ts, src/services/sign-json-rpc-request.ts
=> fix(HW-593): json rpc sign for different networks

src/components/transaction-confirmation/transaction-confirmation.tsx, src/components/typed-data-viewer.tsx
=> fix: Symbol view for typed sign

src/components/account-detail.tsx, src/models/provider/provider-config.ts, src/services/indexer/indexer.types.ts
=> feat(HW-582): Hide bech32 if disabled through remote config

src/components/transaction-sum/transaction-sum.tsx, src/components/ui/sum-block.tsx, src/hooks/use-sum-amount.ts, src/screens/HomeStack/TransactionStack/transaction-sum.tsx
Fixes #
- Incorrect amount on Preview sending for 1000 wISLM
=> fix(HW-603): Incorrect amount on Preview sending for 1000 wISLM

src/components/json-rpc-sign/json-rpc-common-transaction.tsx, src/components/json-rpc-sign/json-rpc-swap-transaction.tsx, src/components/json-viewer.tsx, src/models/tokens.ts, src/screens/SwapStack/swap-screen.tsx, src/screens/settings-developer-tools.tsx
Fixes #
-  swap & tokens optimizations
=> refactor: swap & tokens optimizations

src/models/tokens.ts
Fixes #
-  empty erc20 asset list
=> fix(HW626): empty erc20 asset list

src/components/ui/data-content.tsx, src/components/wallet-row-variant-5.tsx, src/helpers/await-for-wallet.ts
=> fix: hideBalance option fix

src/widgets/ad-widget/index.tsx, src/widgets/banner-widget/index.tsx
Fixes #
- show banner link when dev mode enabled
=> feat: show banner link when dev mode enabled

src/components/account-info/account-info.tsx, src/components/total-value-info/total-value-info.tsx, src/route-types.ts, src/screens/HomeStack/HomeFeedStack/account-info.tsx, src/screens/HomeStack/TransactionStack/transaction-address.tsx, src/screens/total-value-info.tsx
Fixes #
- Open Send screen on tap asset on Tokens screen
=> feat(HW-664): Open Send screen on tap asset on Tokens screen

ios/Podfile.lock, src/components/image-wrapper.tsx, src/components/swap/swap-route-path-icons.tsx, src/components/swap/swap.tsx, src/components/token-viewer/token-viewer.tsx, src/components/transaction-detail.tsx, src/components/transaction-finish.tsx, src/components/transaction-nft-finish.tsx, src/helpers/indexer-transaction-utils.ts, src/helpers/whitelist.ts, src/models/contracts.ts, src/models/currencies.ts, src/models/nft/nft-store.ts, src/models/nft/nft-types.ts, src/screens/HomeStack/HomeFeedStack/transaction-detail.tsx, src/screens/HomeStack/TransactionStack/transaction-nft-confirmation.tsx, src/screens/SwapStack/swap-screen.tsx, src/services/balance.ts, src/services/eth-network/eth-network.ts, src/types.ts, src/widgets/tokens-widget/tokens-widget.tsx
=> fix(HW-704): All Networks RC issues part 2

src/components/token-row.tsx, src/event-actions/on-wallets-balance-check.ts, src/helpers/safe-load-balances.ts, src/models/currencies.ts, src/services/balance.ts, src/services/indexer/indexer.ts, yarn.lock
=> fix: always send correct currency and date to updates_v2

.github/workflows/distribute.yml
Fixes #
- run patch_build only on main branch
=> chore: run patch_build only on main branch

src/services/eth-network/eth-network.ts, src/services/eth-sign.ts, src/services/sign-json-rpc-request.ts
Fixes #
- disable eth_getTransactionCount for tron
=> feat: disable eth_getTransactionCount for tron

.devpkg.js, .devpkg.json, .devpkg.md, hooks/pre-commit, metro.config.js
The DevPkg feature allows developers to override npm packages with local development versions. This is particularly useful when working on multiple interconnected packages simultaneously, enabling real-time testing and debugging of changes across projects.
DevPkg modifies the Metro bundler configuration to prioritize specified local package directories over the versions installed in `node_modules`. This allows you to use development versions of packages without publishing them to npm or manually linking them.
This file contains the configuration for DevPkg. Here's an example structure:
```json
{
"enabled": true,
"packages": {
"your-local-package": {
"path": "/path/to/your/local/package",
"useDevEntryPoint": true
}
}
}
```
- `enabled`: Enables or disables the package overriding.
- …
=> chore: implement devpkg module resolver

src/event-actions/on-deep-link.ts, src/event-actions/on-dynamic-link.ts, src/helpers/web3-browser-utils.ts, src/widgets/tokens-widget/index.tsx
Fixes #
- fixed  browser dynamic link query params
=> fix: browser dynamic link query params

src/models/socket.ts
=> fix(SocketStore): improve socket error handling

src/components/settings/settings-security/settings-security.tsx, src/helpers/is-feature-enabled.ts
=> chore: Hide remove sss button

src/components/news-detail/news-detail.tsx, src/components/transaction-select-crypto/transaction-select-crypto.tsx, src/components/ui/walletCard.tsx, src/hooks/use-layout-animation.tsx, src/models/tokens.ts, src/screens/HomeStack/TransactionStack/transaction-address/transaction-address.tsx, src/screens/transaction-select-crypto.tsx, src/widgets/index.tsx
Fixes #
- Added smooth animations for widgets on the main screen; they now appear and transition fluidly.  
- Removed the "Loading token balances" modal as we now use placeholders when selecting a token.  
- Implemented cache checks during token selection to avoid displaying placeholders unnecessarily.  
- Fixed an issue with identical addresses in API requests (seems resolved).  
- Corrected the "No tokens" message in the token list to ensure it only shows when there are actually no tokens.  
- Updated **Our News**: links now open in the Web3 browser instead of the standard browser.
=> fix: ui improvements
