- package.json
- patches/@ledgerhq+react-native-hw-transport-ble+6.27.9.patch
- yarn.lock
> fix: ledger lib

- src/app.tsx
- src/services/remote-config/remote-config-default-values.ts
- src/services/remote-config/remote-config-service.ts
Fixes #
- fix android initial startup bug
> fix: android initial startup

- src/components/wallets/wallets.tsx
- src/event-actions/on-app-reset.ts
> feat: add rootMnemonicAccountId cache

- src/helpers/get-google-tokens.ts
- src/services/provider-sss.ts
> feat: add google logs [no-verify]

- src/screens/cloud-problems.tsx
> fix: google permissions try again flow

- fastlane/Fastfile
- src/helpers/get-google-tokens.ts
- src/helpers/verify-cloud.ts
- src/screens/cloud-problems.tsx
> fix: Android build status

- src/helpers/get-google-tokens.ts
> fix: remove unused code

- src/components/ui/raffle-block.tsx
- src/widgets/raffles.widget/index.tsx
> fix: raffles widget

- src/components/transaction-detail.tsx
- src/components/transaction-status/transaction-status.tsx
- src/components/transactions/receive.tsx
- src/components/transactions/send.tsx
- src/screens/HomeStack/index.tsx
- src/screens/RootStack/index.tsx
> fix: themes HQM-258

- src/components/singin-restore-wallet/signin-restore-wallet.tsx
- src/components/ui/button.tsx
- src/components/ui/error-text.tsx
- src/screens/WelcomeStack/SignInStack/signin-restore-wallet.tsx
> fix: onDoneTry hook deps

- src/components/popup-header.tsx
> fix: New header insets on android

- src/components/in-app-browser.tsx
> fix: android crash

- src/helpers/get-google-tokens.ts
> feat: add (return) google silent login

- src/components/json-rpc-sign.tsx
- src/components/web3-browser/web3-browser.tsx
- src/debug-vars.ts
- src/helpers/modal.ts
- src/helpers/whitelist.ts
- src/screens/HomeStack/JsonRpcSignPopupStack/json-rpc-sign-screen.tsx
- src/services/remote-config/remote-config-default-values.ts
- src/variables/common.ts
Fixes #
- white list sign operations
> fix: white list sign operations

- src/services/remote-config/remote-config-service.ts
> feat: add app info log

- src/helpers/get-leading-account.ts
- src/services/remote-config/remote-config-service.ts
> fix: remote config fetch

- src/components/popup-header.tsx
- src/screens/HomeStack/HomeFeedStack/create.tsx
- src/screens/HomeStack/index.tsx
- src/screens/WelcomeStack/OnboardingStack/index.tsx
> fix: Revert some headers' fixes

- src/screens/WelcomeStack/SignUpStack/signup-store-wallet.tsx
- src/screens/sss-store-wallet.tsx
> fix: new wallets names

- src/app.tsx
- src/event-actions/on-wallet-remove.ts
- src/screens/WelcomeStack/OnboardingStack/onboarding-finish.tsx
> fix: onboarding navigation

- src/components/popup-header.tsx
- src/helpers/get-news-detail-title.tsx
- src/screens/HomeStack/HomeNewsStack/index.tsx
> fix: New header for news popups

- src/helpers/get-google-tokens.ts
- src/helpers/verify-cloud.ts
- src/i18n.ts
- src/screens/WelcomeStack/SignUpStack/signup-networks.tsx
- src/screens/cloud-problems.tsx
- src/services/provider-sss.ts
- src/services/remote-config/remote-config-service.ts
> fix: remove sss logs

- src/i18n.ts
> feat: update text

- android/app/build.gradle
- ios/haqq/Info.plist
> feat: update version

- package.json
- src/components/bottom-sheet.tsx
- src/components/signup-important-info.tsx
- src/components/signup-network-exists/signup-network-exists.tsx
- src/components/ui/button.tsx
- src/components/ui/text.tsx
- src/helpers/get-google-tokens.ts
- src/i18n.ts
- src/screens/WelcomeStack/SignUpStack/index.tsx
- src/screens/WelcomeStack/SignUpStack/signup-important-info.tsx
- src/screens/WelcomeStack/SignUpStack/signup-network-exists.tsx
- src/screens/WelcomeStack/SignUpStack/signup-networks.tsx
- yarn.lock
> feat: add important info screen

- src/components/choose-account/choose-account-row.tsx
Fixes #
- choose  account button
> fix: choose account button

- src/components/bottom-sheet.tsx
- src/components/signup-network-exists/signup-network-exists.tsx
- src/i18n.ts
- src/screens/WelcomeStack/SignUpStack/signup-network-exists.tsx
> fix: modal

- src/components/bottom-sheet.tsx
- src/screens/HomeStack/SssMigrate/index.tsx
- src/screens/HomeStack/SssMigrate/sss-migrate-networks.tsx
- src/screens/HomeStack/SssMigrate/sss-migrate-rewrite.tsx
- src/screens/HomeStack/SssMigrate/sss-migrate-store.tsx
- src/screens/WelcomeStack/SignUpStack/signup-store-wallet.tsx
> fix: sss ui

- src/components/bottom-sheet.tsx
- src/components/signup-network-exists/signup-network-exists.tsx
- src/components/sss-migrate-rewrite/sss-migrate-rewrite.tsx
> fix: modals

- src/components/popup-header.tsx
> fix: total info header border radius

- src/helpers/modal.ts
Fixes #
- fix for raffle agrement modal
> fix: awaitForPopupClosed

- src/components/signup-network-exists/signup-network-exists.tsx
- src/components/sss-migrate-rewrite/sss-migrate-rewrite.tsx
- src/helpers/get-wallets-from-provider.tsx
- src/models/wallet.ts
- src/screens/WelcomeStack/SignInStack/signin-store-wallet.tsx
- src/screens/choose-account-screen.tsx
- src/screens/sss-store-wallet.tsx
> fix: new wallets name

- src/screens/WelcomeStack/SignUpStack/signup-store-wallet.tsx
> fix: cannot read property getIdentifier of undefined

- src/components/modals/cloud-share-not-found.tsx
- src/helpers/get-provider-for-new-wallet.ts
- src/helpers/wrappers/get-metadata-value.ts
- src/models/error-handler.ts
- src/screens/HomeStack/SssMigrate/sss-migrate-networks.tsx
- src/screens/HomeStack/SssMigrate/sss-migrate-store.tsx
- src/screens/WelcomeStack/SignInStack/signin-store-wallet.tsx
- src/screens/WelcomeStack/SignUpStack/signup-networks.tsx
- src/screens/WelcomeStack/SignUpStack/signup-store-wallet.tsx
- src/screens/sss-store-wallet.tsx
> feat: add sss limit logging

- src/components/ui/button.tsx
> feat: add debounce for button onPress

- .gitignore
- e2e/1_signup.test.ts
- e2e/3_routine.test.ts
- e2e/4_settings.test.ts
- e2e/5_wallet_reset.test.ts
- e2e/helpers/createWallet.ts
- e2e/helpers/restoreWallet.ts
- package.json
- yarn.lock
> fix: e2e tests

- src/components/finish.tsx
- src/components/lottie/index.tsx
> fix(HQM-271): animations

- src/components/lottie/index.tsx
> feat: speedup animations

- src/components/signup-important-info.tsx
- src/i18n.ts
> fix: texts

- src/screens/HomeStack/BrowserStack/browser-home-page-screen.tsx
> fix: HAQQ Dashboard bookmark icon

- src/helpers/provider-instance.ts
> fix: remove provider cache

- src/screens/WelcomeStack/SignUpStack/signup-store-wallet.tsx
> fix: sss restore flow

- src/models/web3-browser-bookmark.ts
- src/screens/HomeStack/BrowserStack/browser-home-page-screen.tsx
- src/services/remote-config/remote-config-default-values.ts
- src/types.ts
> feat: add bookmark adjust event HQM-287

- src/components/modals/cloud-share-not-found.tsx
Fixes #
https://haqq-network.sentry.io/issues/4773831247/
-
-
-
> fix: crash HQM-286

- src/services/push-notifications.ts
> fix: android crash with missing gapps

- src/models/index.ts
> fix: realm migration

- ios/Podfile.lock
- patches/react-native+0.72.4.patch
Fixes #
React Native Patch due to issue https://github.com/boostorg/boost/issues/843
> fix: React Native Patch due to issue

- src/screens/HomeStack/HomeNewsStack/home-news.tsx
- src/screens/HomeStack/home.tsx
> fix: news updates

- src/components/locked-tokens.tsx
- src/components/token-row.tsx
- src/components/total-value-info/total-value-info-header.tsx
- src/components/transaction-confirmation/transaction-confirmation.tsx
- src/components/transaction-detail.tsx
- src/components/transactions/contract.tsx
- src/components/transactions/receive.tsx
- src/components/transactions/send.tsx
- src/components/ui/sum-block.tsx
- src/components/wallet-card.tsx
- src/i18n.ts
- src/services/balance.ts
- src/services/exchange-rates.ts
- src/widgets/transactions-widget/transaction-row-widget.tsx
> feat: add fiat balance support

- src/components/account-info/account-info.tsx
- src/components/token-viewer/token-viewer.tsx
- src/components/ui/walletCard.tsx
- src/screens/HomeStack/HomeFeedStack/account-info.tsx
> feat: add token support on account info

- .github/workflows/distribute-android.yml
- .github/workflows/distribute-ios.yml
- .github/workflows/distribute.yml
> fix: build

- src/components/home-staking/home-staking.tsx
- src/components/home-staking/staking-active.tsx
- src/components/home-staking/staking-empty.tsx
- src/components/json-rpc-sign.tsx
- src/components/staking-delegate-finish/staking-delegate-finish.tsx
- src/components/staking-delegate-preview/staking-delegate-preview.tsx
- src/components/staking-info/staking-info.tsx
- src/components/staking-validators/validator-row.tsx
- src/widgets/ad-widget/index.tsx
- src/widgets/banner-widget/index.tsx
> feat: add test ids HQM-291

- src/components/home-banner.tsx
- src/models/banner.ts
- src/utils.ts
Fixes #
- HQM-299: hide close button if closeEvent equals `none`
> feat: banners with none closeEvent

- src/screens/HomeStack/ManageAccountsStack/settings-view-recovery-phrase.tsx
> fix: cloud storage

- src/event-actions/on-wallet-sss-check.ts
> fix: onWalletSSSCheck

- src/services/balance.ts
> fix: Remove makeAutoObservable from Balance to fix cyclic re-renders

- .eslintignore
Fixes #
- eslint ignore node modules
> feat: eslint ignore node modules

- src/components/locked-tokens.tsx
- src/components/wallet-card.tsx
> feat: update balance ui

- src/components/home-news.tsx
- src/components/news/news-card.tsx
- src/components/news/news-row.tsx
- src/components/popup/dismiss-popup-button.tsx
- src/screens/HomeStack/home.tsx
Fixes #hqm-304
- add test ids
-
-
> test: #hqm-304 add test id

- src/app.tsx
Fixes #
-  navigation after reset wallet
> fix: navigation after reset wallet

- e2e/3_routine.test.ts
- e2e/9_change_pin.test.ts
- e2e/helpers/changePIN.ts
Fixes #
- added 'change pin' test
- added 'change pin' helper
> test: added test for change pin

- src/components/staking-validators/staking-validators.tsx
- src/components/ui/custom-header/custom-header.tsx
> feat: validators button testId

- src/screens/DeviceStack/KeystoneStack/index.tsx
- src/screens/DeviceStack/LedgerStack/index.tsx
- src/screens/DeviceStack/index.tsx
- src/screens/HomeStack/BackupStack/index.tsx
- src/screens/HomeStack/JsonRpcSignPopupStack/index.tsx
- src/screens/HomeStack/SssMigrate/index.tsx
- src/screens/HomeStack/TransactionStack/index.tsx
- src/screens/HomeStack/WalletConnectApprovalStack/index.tsx
- src/screens/HomeStack/index.tsx
- src/screens/WelcomeStack/OnboardingStack/index.tsx
- src/screens/WelcomeStack/SignInStack/index.tsx
- src/screens/WelcomeStack/SignUpStack/index.tsx
- src/screens/WelcomeStack/index.tsx
Fixes #
- fixed theme HOC listener for screens
> fix: theme HOC listener for screens

- src/components/keystone/keystone-connection-steps.tsx
- src/hooks/use-open-in-app-browser.ts
- src/i18n.ts
- src/screens/DeviceStack/KeystoneStack/keystone-connection-steps.tsx
- src/utils.ts
- src/variables/common.ts
Fixes #
- rename default keystone name "QR Hardware" -> keystone 
- fix open in app browser for keystone tutorial
- fix translations
> fix: keystone

- src/components/account-info/account-info.tsx
- src/components/top-tab-navigator-large.tsx
- src/components/top-tab-navigator-small.tsx
- src/components/top-tab-navigator.tsx
- src/components/transaction-row.tsx
- src/components/transactions/contract.tsx
- src/components/wallet-card.tsx
> feat(HQM-306): Add test ids

- e2e/7_coin_delegation.test.ts
Fixes #
- added delegate coins test
- added undelegate coins test
> test: added coin delegation/undelegation test

- src/components/wallets/wallets.tsx
- src/contexts/app.ts
- src/event-actions/on-app-reset.ts
- src/event-actions/on-block-request-check.ts
- src/event-actions/on-dynamic-link.ts
- src/event-actions/on-push-subscription-transactions-subscribe.ts
- src/event-actions/on-push-subscription-transactions-unsubscribe.ts
- src/event-actions/on-wallet-remove.ts
- src/helpers/get-app-info.ts
- src/helpers/get-leading-account.ts
- src/helpers/webview-geolocation.ts
- src/helpers/whitelist.ts
- src/hooks/use-variables-string.ts
- src/hooks/use-webview-shared-props.tsx
- src/models/index.ts
- src/models/realm-object-for-migration.ts
- src/models/variables-string.ts
- src/screens/HomeStack/SettingsStack/settings-test.tsx
- src/services/push-notifications.ts
- src/services/remote-config/remote-config-service.ts
- src/services/wallet-connect.ts
- src/widgets/index.tsx
Reverts haqq-network/haqq-wallet#1630
> Revert "feat: Migrate StringsVariable from Realm into MobX"

- android/app/src/main/AndroidManifest.xml
- ios/Podfile.lock
> fix: low end android

- src/components/home-feed.tsx
- src/models/stories.ts
- src/services/backend.ts
- src/types.ts
> feat: Stories store

- src/components/home-feed.tsx
- src/components/stories/index.tsx
- src/components/stories/stories-loader-item.tsx
- src/components/stories/stories-preview-item.tsx
- src/components/stories/stories-wrapper.tsx
- src/models/stories.ts
- src/types/env.d.ts
> feat: add stories preview and loading components

- src/helpers/get-remote-balance-value.tsx
- src/services/cosmos.ts
- src/services/eth-network.ts
- src/services/remote-config/remote-config-default-values.ts
- src/services/remote-config/remote-config-types.ts
> fix: Fix commission calculations for cosmos and eth

- src/services/json-rpc-middleware/json-rpc-methods-handlers.ts
Fixes #
- web3 browser estimate gas
> fix: web3 browser estimate gas

- src/services/eth-network.ts
Fixes #
-  erc20 tokens gas calculation
> fix: erc20 tokens gas calculation

- src/helpers/indexer-transaction-utils.ts
- src/types.ts
- src/variables/common.ts
Fixes #
- tx IBC token contract
> fix: tx IBC token contract

- src/components/token-row.tsx
- src/components/transaction-confirmation/transaction-confirmation.tsx
- src/components/transaction-detail.tsx
- src/components/transaction-finish.tsx
- src/components/transaction-sum/transaction-sum.tsx
- src/helpers/indexer-transaction-utils.ts
- src/models/tokens.ts
Fixes #
-  HQM-328 erc20 tokens ui
> fix: erc20 tokens ui

- src/services/json-rpc-middleware/json-rpc-methods-handlers.ts
- src/services/remote-config/remote-config-default-values.ts
Fixes #
- implements keplr sign amino
> feat: implements keplr sign amino

- src/services/eth-network.ts
Fixes #
- decimals erc20 tokens transfer
> fix: decimals erc20 tokens transfer

- src/services/json-rpc-middleware/json-rpc-methods-handlers.ts
Fixes #
- keplr amino signature
> fix: keplr amino signature

- src/services/eth-network.ts
Fixes #
-  transfer tokens decimals
> fix: transfer tokens decimals

- src/components/image-wrapper.tsx
- src/components/nft-collection-details.tsx
- src/components/nft-item-details.tsx
- src/components/site-icon-preview.tsx
- src/components/token-row.tsx
- src/components/transaction-detail.tsx
- src/components/transaction-list/transaction-row.tsx
Fixes #
- added image wrapper to fix `property is not configurable`
> fix: property is not configurable

- ios/Podfile.lock
- src/components/link-preview-square.tsx
Fixes #
- center link preview square title and add margin-top
> fix: center link preview square title and add margin-top

- metro.config.js
Fixes #
- fix for resolution of module imports in metro.config.js
> fix: resolution of module imports in metro.config.js

- src/components/ui/text.tsx
> feat: add position and variant Text prop support

- ios/Podfile.lock
- src/components/stories/stories-wrapper.tsx
- src/components/stories/story-view/components/story-list.tsx
- src/components/stories/story-view/components/story-overlay.tsx
- src/components/stories/story-view/core/dto/storiesViewDTO.ts
- src/screens/HomeStack/HomeFeedStack/home-stories.tsx
- src/types.ts
> feat: implement StoryOverlay

- src/components/stories/story-view/components/story-video.tsx
> feat: add ignoreSilentSwitch

- .github/workflows/e2e.yml
- .github/workflows/e2e_android.yml
- .github/workflows/e2e_ios.yml
> fix: e2e actions

- src/components/signup-network-exists/signup-network-exists.tsx
- src/screens/WelcomeStack/SignUpStack/index.tsx
> fix: ui bug

- package.json
Fixes #
- add --error-on-fail flag to patch-package
> feat: add --error-on-fail flag to patch-package

- hooks/pre-commit
Fixes #
-  run patch-package in pre-commit hook
> feat: run patch-package in pre-commit hook

- src/components/home-feed.tsx
- src/components/stories/stories-wrapper.tsx
- src/models/stories.ts
> fix: stutters on home screen

- src/components/web3-browser/web3-browser-container.tsx
- src/components/web3-browser/web3-browser.tsx
Fixes #
- implements keyboard avoid for web3 browser
> feat: implements keyboard avoid for web3 browser

- src/components/ui/text-field.tsx
Fixes #
- autofocus issue in TextField component
> fix: autofocus issue in TextField component

- src/components/web3-browser/web3-browser-container.tsx
- src/hooks/use-keyboard-dismiss-in-background.tsx
Fixes #
- fix for subscriptions remove
-
-
> fix: subscriptions remove

- src/components/in-app-browser.tsx
- src/components/web3-browser/web3-browser-container.tsx
Fixes #
- implement keyboard avoid for browsers
> fix: implement keyboard avoid for browsers

- src/event-actions/on-wallet-connect-sign-transaction.ts
- src/services/json-rpc-middleware/json-rpc-methods-handlers.ts
Fixes #
-  implement switchEthereumChain handling
> feat(WalletConnect): implement switchEthereumChain handling

- src/hooks/use-toast.tsx
- src/screens/HomeStack/TransactionStack/transaction-confirmation.tsx
- src/services/eth-network.ts
> fix: error handling

- src/components/transaction-list/transaction-list.tsx
- src/services/remote-config/remote-config-default-values.ts
- src/services/remote-config/remote-config-types.ts
Fixes #
- add transaction section headers based on remote configuration
> feat: add transaction section headers based on remote configuration

- src/models/transaction.ts
Fixes #
-  temp caching transactions in TransactionStore
> feat: temp caching transactions in TransactionStore

- src/components/token-row.tsx
- src/components/transaction-list/transaction-row.tsx
- src/services/balance.ts
Fixes #
- fix tokens toBalanceString for fixed number
> fix: tokens toBalanceString for fixed number

- .github/workflows/distribute-android.yml
- .github/workflows/distribute.yml
> feat: update runner

- src/components/account-info/account-info-header.tsx
- src/components/locked-tokens.tsx
- src/components/token-row.tsx
- src/components/total-value-info/total-value-info-header.tsx
- src/components/transaction-confirmation/transaction-confirmation.tsx
- src/components/transaction-detail.tsx
- src/components/transaction-list/transaction-row.tsx
- src/components/ui/sum-block.tsx
- src/components/wallet-card.tsx
- src/models/currencies.ts
- src/services/balance.ts
> fix: Hide fiat equivalent if currency rate unknown

- .github/workflows/distribute-android.yml
- .github/workflows/distribute.yml
Reverts haqq-network/haqq-wallet#1695
> feat: revert update runner

- src/services/json-rpc-middleware/json-rpc-methods-handlers.ts
Fixes #
- determine number type in EIP712 message handler
> feat: determine number type in EIP712 message handler

- src/debug-vars.ts
- src/models/tokens.ts
Fixes #
-  added axelar usdc faucet tokens
> refactor: hardcoded erc20 tokens

- src/helpers/whitelist.ts
- src/screens/settings-developer-tools.tsx
Fixes #
- developer tools disable cache for verify contract
> refactor: developer tools disable cache for verify contract

- src/services/eth-sign.ts
- src/services/sign-json-rpc-request.ts
> fix: json rpc sign

- src/screens/WelcomeStack/SignInStack/signin-store-wallet.tsx
> fix: private key import

- src/components/web3-browser/web3-browser-helper.ts
- src/components/web3-browser/web3-browser.tsx
- src/services/eth-sign.ts
- src/services/sign-json-rpc-request.ts
> fix: web3 browser

- src/components/modals/keystone/keystone-qr.tsx
Fixes #
-  update QR code change interval for Android
> fix: update keystone QR code change interval for Android

- src/components/stories/story-view/components/story-container.tsx
> fix: remove GestureHandler

- ios/haqq.xcodeproj/project.pbxproj
- src/components/settings/settings-currency/settings-currency.tsx
- yarn.lock
> fix: Update currency settings design

- src/components/stories/story-view/components/story-container.tsx
> fix: stories animation

- src/components/settings/settings-currency/settings-currency.tsx
- src/event-actions/on-app-initialized.ts
- src/event-actions/on-wallets-balance-check.ts
- src/models/currencies.ts
- src/services/indexer.ts
> fix: Rates change updates

- src/components/wallet-card.tsx
- src/models/currencies.ts
> fix: Correct fiat calculation when app opens first time

- src/event-actions/on-provider-changed.ts
- src/models/currencies.ts
> fix: Re-calculate rates when provider changed

- src/components/wallet-protection.tsx
Fixes #
- Update deprecated props for Text on Wallet Protection screen
- Fix icon name declaration
-
> fix: Protect your account screen updates

- src/contexts/app.ts
- src/events.ts
- src/screens/HomeStack/home.tsx
> fix: HQM-350

- src/helpers/check-app-version.ts
> fix: TypeError Cannot read property match of undefined #1723

- src/components/token-viewer/token-viewer.tsx
- src/components/total-value-info/total-value-info-header.tsx
- src/components/total-value-info/total-value-info.tsx
- src/components/transaction-list/transaction-list.tsx
- src/components/ui/data-content.tsx
- src/components/ui/walletCard.tsx
- src/helpers/get-wallet-title.ts
- src/screens/HomeStack/index.tsx
> fix: ui HQM-347

- package.json
- src/contexts/app.ts
- src/helpers/secure-pin-utils.ts
- yarn.lock
Fixes #
- fixed update pin for hot wallet provider
> fix: update pin for hot wallet provider

- .detoxrc.js
- e2e/3_routine.test.ts
- e2e/4_settings.test.ts
- e2e/globalSetup.ts
- e2e/globalTeardown.ts
- e2e/helpers/checkMilkAddressBalance.ts
- e2e/helpers/getCoins.ts
- e2e/helpers/milkAddressProxy.ts
- e2e/init.ts
- e2e/jest.config.js
- e2e/test-variables.ts
> feat: add MilkAddressProxy

- src/components/json-rpc-transaction-info.tsx
- src/screens/HomeStack/JsonRpcSignPopupStack/json-rpc-sign-screen.tsx
- src/screens/HomeStack/TransactionStack/transaction-confirmation.tsx
- src/services/eth-network.ts
- src/services/eth-sign.ts
- src/services/sign-json-rpc-request.ts
- src/utils.ts
- src/variables/balance.ts
Fixes #
-  fee calculation for tx from dapp
> refactor: fee calculation for tx from dapp

- src/app.tsx
- src/event-actions/on-app-initialized.ts
- src/models/currencies.ts
> fix: Update currencies rates flow

- src/contexts/app.ts
> fix: isUnlocked flag

- src/services/balance.ts
> fix: Unexpected convertation to fiat string

- src/components/settings/settings-currency/currency-header.tsx
- src/components/settings/settings-currency/settings-currency.tsx
- src/screens/HomeStack/SettingsStack/index.tsx
- src/screens/HomeStack/SettingsStack/settings-currency.tsx
> fix: Update currencies settings screen styles

- src/app.tsx
- src/event-actions/on-app-initialized.ts
> fix: Fix currency select on very first run

- src/components/settings/settings-currency/settings-currency.tsx
> fix: currency flat list

- src/event-actions/on-app-initialized.ts
- src/models/currencies.ts
Fixes #
- fix default currency
> fix: default currency

- src/components/transaction-sum/transaction-sum.tsx
- src/screens/HomeStack/TransactionStack/transaction-sum.tsx
Fixes #
-  fee confirmation error
> fix: fee confirmation error

- src/contexts/app.ts
> fix: default network

- src/screens/DeviceStack/KeystoneStack/index.tsx
- src/screens/DeviceStack/LedgerStack/index.tsx
Fixes #
- crash in OnboardingStackGenerated when create new account
> fix: crash in OnboardingStackGenerated when create new account

- src/event-actions/on-wallets-balance-check.ts
- src/screens/DeviceStack/KeystoneStack/keystone-accounts.tsx
- src/screens/choose-account-screen.tsx
Fixes #
- currency rates updates
> fix: currency rates updates

- src/event-actions/on-wallets-balance-check.ts
- src/models/currencies.ts
- src/types.ts
> fix: currency rates

- src/screens/HomeStack/index.tsx
> feat: update gestureEnabled to false

- src/components/account-info/account-info-header.tsx
- src/components/token-row.tsx
- src/components/transaction-detail.tsx
- src/components/transaction-list/transaction-row.tsx
- src/components/wallet-card/balance-info-details.tsx
- src/components/wallet-card/balance-info-total.tsx
- src/services/balance.ts
> feat: Show ISLM and use currency as additional info on main card

- metro.config.js
> fix: metro config

- src/components/json-rpc-sign-info.tsx
- src/components/json-rpc-sign.tsx
- src/components/json-rpc-transaction-info.tsx
- src/components/json-viewer.tsx
- src/components/typed-data-viewer.tsx
- src/i18n.ts
- src/services/cosmos.ts
- src/types.ts
- src/utils.ts
Fixes #
-  added parsing for delegate, undelegate, redelegate, claim_rewords
> feat: parsing cosmos tx

- src/i18n.ts
- src/services/wallet-connect.ts
Fixes #
- wallet connect errors
> fix: wallet connect errors

- src/event-actions/on-wallet-connect-uri.ts
Fixes #
- WC pairing loading indicator
> feat: WC pairing loading indicator

- src/i18n.ts
- src/services/wallet-connect.ts
Fixes #
- wallet connect error handling, show modal instead of toast
> feat: wallet connect error handling, show modal instead of toast

- src/models/stories.ts
> fix: remove stories cache

- src/models/stories.ts
> fix: stories cache

- ios/Podfile.lock
- src/event-actions/on-deep-link.ts
- src/event-actions/on-wallet-connect-uri.ts
- src/i18n.ts
- src/services/wallet-connect.ts
Fixes #
- feat: handle requestId in wallet connect
> feat: handle requestId in wallet connect

- src/services/wallet-connect.ts
Fixes #
- select current active chain for wallet connect
> feat: select current active chain for wallet connect

- src/components/stories/story-view/components/story-container.tsx
> feat: add swipeDown and onPressOut gestures

- src/contexts/app.ts
> fix: biometric auth multiple calls

- src/components/ui/text-field.tsx
Fixes #
- fixed android app not responding when TextFIeld use autofocus
> fix(TextField): android app not responding

- src/components/transaction-address.tsx
- src/route-types.ts
- src/screens/HomeStack/TransactionStack/transaction-address.tsx
- src/screens/HomeStack/TransactionStack/transaction-sum-address.tsx
- src/screens/HomeStack/TransactionStack/transaction-sum.tsx
Fixes #
-  address done on enter
> feat: tx address done on press enter

- .github/workflows/e2e_android.yml
Fixes #
-  android e2e show touches
> feat: android e2e show touches

- src/components/ledger-accounts/ledger-accounts-row.tsx
- src/helpers/safe-load-balances.ts
- src/screens/DeviceStack/KeystoneStack/keystone-accounts.tsx
- src/screens/DeviceStack/LedgerStack/ledger-accounts.tsx
- src/screens/choose-account-screen.tsx
- src/types.ts
Fixes #
- balance fetching fallback to RPC when Indexer.updates got error
> fix(ImportAccounts): balance fetching fallback to RPC when Indexer.updates got error

- src/app.tsx
- src/components/app-version-absolute-view.tsx
> feat: show app version

- android/app/build.gradle
- ios/haqq/Info.plist
- package.json
> chore: up version

- src/components/app-version-absolute-view.tsx
- src/components/ui/custom-header/custom-header.tsx
- src/types/global.d.ts
Fixes #
- [feat: add useSafeAreaFrame hook in CustomHeader](https://github.com/haqq-network/haqq-wallet/commit/2f824d2dc7def9b213ecf8b255edd2ad10d5178b)
- [feat: add ModalProvider to app version absolute view](https://github.com/haqq-network/haqq-wallet/commit/ec47521b4f964b30f27d50a9c3f1a4aee36eeab5)
- [chore: remove redundant declaration for react-native-safe-area-context](https://github.com/haqq-network/haqq-wallet/commit/a82fb0652b2e31af493e3b2526302b83edf37513)
> fix: ui fixes

- src/components/modals/modal-wrapper.tsx
Fixes #
-  disable unnecessary modal auto close
> fix: disable unnecessary modal auto close

- e2e/4_settings.test.ts
> feat: add new test

- e2e/3_routine.test.ts
- e2e/4_settings.test.ts
> feat: add "should import mnemonic with duplicated word and see valid phrase in settings" test

- package.json
Fixes #
- script to empty force push commit
> feat: script to empty force push commit

- e2e/4_settings.test.ts
> fix: duplicate mnemonic case

- src/services/toast.ts
> fix: android toast

- src/helpers/modal.ts
Fixes #
-  dismiss keyboard on modal show
> feat: dismiss keyboard on modal show

- package.json
- yarn.lock
> chore: update minifyer

- .github/workflows/e2e_android.yml
Fixes #
- enable dev mode on android e2e emulator
> feat: enable dev mode on android e2e emulator

- e2e/3_routine.test.ts
- e2e/7_coin_delegation.test.ts
Fixes #
- 3_routine.test wait for input focus
> fix: 3_routine.test wait for input focus

- android/app/build.gradle
- ios/haqq/Info.plist
- package.json
> chore: up vesion

- src/components/locked-tokens.tsx
- src/components/wallet-card/balance-info-details.tsx
- src/components/wallet-card/balance-info-total.tsx
- src/components/wallet-card/wallet-card.tsx
- src/event-actions/on-wallets-balance-check.ts
- src/hooks/use-is-balances-sync.ts
Fixes #
- fixed balance skeleton placeholder
> fix: balance skeleton placeholder

- android/app/build.gradle
- ios/haqq/Info.plist
- package.json
> chore: up version to 1.7.0

- package.json
- src/helpers/whitelist.ts
- src/services/indexer.ts
- src/services/remote-config/remote-config-default-values.ts
- src/services/remote-config/remote-config-types.ts
- yarn.lock
Fixes #
- send indexer HTTP errors to Sentry
> feat: send indexer HTTP errors to Sentry

- src/components/ui/text-field.tsx
> fix(#1806): ApplicationNotResponding: ANR for at least 5000 ms

- scripts/update-version.mjs
> feat: testting releaseAfterMerge flag

- fastlane/Fastfile
> fix: fastlane

- .github/workflows/distribute.yml
> fix: quotes

- src/hooks/use-webview-shared-props.tsx
Fixes #
-  send posthog distinct id to browser
> feat: send posthog distinct id to browser

- src/event-actions/on-dynamic-link.ts
Fixes #
-  dynamic link posthog integration
> feat: dynamic link posthog integration

- src/screens/HomeStack/home.tsx
> fix: navigation to settings

- ios/Podfile.lock
- package.json
- src/components/stories/stories-preview-item.tsx
- src/event-actions/on-app-reset.ts
- src/models/stories.ts
- src/types/global.d.ts
- yarn.lock
> feat: add stories preview image cache

- src/types.ts
> fix: fcm ts types

- .gitignore
- src/contexts/app.ts
- src/services/provider-sss.ts
- src/services/remote-config/remote-config-default-values.ts
- src/services/remote-config/remote-config-types.ts
> fix: providers

- src/hooks/use-is-balances-sync.ts
Fixes #
- fixed balance placeholder
[movie.ogg](https://github.com/haqq-network/haqq-wallet/assets/25716589/2d863530-2ec3-4f64-b56e-44998e25b115)
> fix: balance placeholder

- src/components/app-version-absolute-view.tsx
Fixes #
-  app version absolute view
> fix: app version absolute view

- src/components/account-info/account-info.tsx
- src/components/locked-tokens.tsx
- src/components/nft-viewer/nft-viewer.tsx
- src/components/total-value-info/total-value-info.tsx
- src/components/wallet-card/wallet-card.tsx
- src/event-actions/on-provider-changed.ts
- src/hooks/use-is-balances-sync.ts
- src/models/nft/nft-store.ts
Fixes #
- Remove NFTs caching
- Re-fetch NFTs when provider changed
- Filter NFTs by wallet address
- Fix typos
> feat(nft): Filter NFTs by provider and selected wallet

- .github/workflows/distribute-android.yml
- .github/workflows/distribute-ios.yml
- .github/workflows/distribute.yml
- .github/workflows/e2e.yml
- .github/workflows/e2e_android.yml
- .github/workflows/e2e_ios.yml
- .github/workflows/generate-release-notes.yml
- .github/workflows/main.yml
- .github/workflows/merged-action.yml
- ios/Podfile.lock
- ios/haqq.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
- src/components/total-value-info/total-value-info.tsx
- src/helpers/is-feature-enabled.ts
- src/types/env.d.ts
> feat(nft): Enable/disable nft feature through env variables

- src/ar.ts
- src/i18n.ts
- src/screens/HomeStack/TransactionStack/transaction-sum.tsx
> fix: estimate gas modal

- package.json
Fixes #
- update version to 1.6.4
> chore: update version to 1.6.4

- src/services/event-tracker.ts
Fixes #
- posthog user friedly names
> feat: posthog user friendly event names

- src/components/locked-tokens.tsx
- src/components/wallet-card/balance-info-details.tsx
- src/components/wallet-card/balance-info-total.tsx
Fixes #
- balance placeholder height
> fix: balance placeholder height

- src/components/locked-tokens.tsx
- src/components/ui/badge.tsx
- src/components/ui/text.tsx
> fix: Update locked tokens badge text variant

- src/components/transaction-list/transaction-section-header.tsx
Fixes #
- added background to transaction list (iOS) for sticky date header
> fix: tx list iOS sticky date header bg

- package.json
Fixes #
- update version to 1.7.0
> chore: update version to 1.7.0

- src/helpers/get-app-info.ts
Fixes #
- send AD ID to backend
> feat: send AD ID to backend

- src/models/nft/nft-store.ts
- src/models/nft/nft-types.ts
- src/screens/HomeStack/NftDetailsStack/components/nft-item-details/components/nft-item-details-attributes.tsx
- src/screens/HomeStack/NftDetailsStack/components/nft-item-details/nft-item-details.tsx
- src/services/eth-network/types.ts
> feat: (HQM-382) NFT properties

- src/components/transaction-nft-confirmation.tsx
- src/models/nft/nft-store.ts
- src/screens/HomeStack/TransactionStack/transaction-nft-confirmation.tsx
- src/services/eth-network/erc1155.ts
- src/services/eth-network/eth-network.ts
> fix(HQM-385): NFT UI fixes

- src/components/nft-viewer/nft-viewer-section-header.tsx
> fix: Show collection image into collections grid view

- src/widgets/nft-widget/components/index.ts
- src/widgets/nft-widget/components/nft-collection-view.tsx
- src/widgets/nft-widget/components/nft-list-view.tsx
- src/widgets/nft-widget/index.tsx
> refactor: Nft widget

- src/components/nft-collection-details.tsx
> fix(HQM-391): Fix nft collection image resize mode

- src/components/nft-viewer/nft-viewer.tsx
- src/components/total-value-info/total-value-info.tsx
- src/route-types.ts
- src/screens/HomeStack/HomeFeedStack/index.tsx
- src/screens/HomeStack/NftStack/index.tsx
- src/screens/HomeStack/TransactionStack/transaction-nft-finish.tsx
- src/screens/HomeStack/index.tsx
> fix(HQM-392): Navigate to HomeFeed after successful transaction

- src/components/in-app-browser.tsx
Fixes #
- in-app browser double cross
> fix: in-app browser double cross

- src/components/transaction-nft-confirmation.tsx
- src/models/nft/nft-store.ts
- src/models/nft/nft-types.ts
- src/types.ts
> feat: Dismiss transfer for non-transferable tokens

- src/components/transaction-nft-confirmation.tsx
- src/components/transaction-nft-finish.tsx
- src/components/ui/data-view.tsx
- src/route-types.ts
- src/screens/HomeStack/NftStack/components/nft-item-details/nft-item-details.tsx
- src/screens/HomeStack/NftStack/index.tsx
- src/screens/HomeStack/TransactionStack/transaction-address.tsx
- src/screens/HomeStack/TransactionStack/transaction-nft-confirmation.tsx
- src/screens/HomeStack/TransactionStack/transaction-nft-finish.tsx
> fix(HQM-394): NFT fixes UI&FEE

- src/screens/HomeStack/TransactionStack/transaction-nft-finish.tsx
> fix: Contact address when save it after nft transfer

- src/screens/HomeStack/TransactionStack/transaction-nft-finish.tsx
> fix: Save account address instead of contract

- src/models/nft/nft-types.ts
- src/screens/HomeStack/NftStack/components/nft-item-details/components/nft-item-details-attributes.tsx
- src/screens/HomeStack/NftStack/components/nft-item-details/nft-item-details.tsx
> fix: Change NFT properties to attributes from metadata

- src/components/account-info/account-info.tsx
- src/components/top-tab-navigator-large.tsx
- src/components/total-value-info/total-value-info.tsx
> fix: animation

- src/components/nft-viewer/nft-viewer-collection-preview.tsx
- src/components/nft-viewer/nft-viewer-item-preview-large.tsx
- src/components/nft-viewer/nft-viewer-item-preview-medium.tsx
- src/components/nft-viewer/nft-viewer-item-preview-small.tsx
- src/components/nft-viewer/nft-viewer.tsx
> fix: Nft item container as square

- src/components/transaction-list/transaction-row.tsx
- src/components/wallet-card/balance-info-details.tsx
- src/components/wallet-card/balance-info-total.tsx
- src/components/wallet-card/wallet-card.tsx
Fixes #
- Shrink clickable area of wallet card
- Use TouchableOpacity for press effects on transaction row
> fix(HQM-348): Update UI styles

- ios/haqq.xcodeproj/project.pbxproj
- ios/haqq/Info.plist
> chore(): remove unknown ip

- src/screens/HomeStack/SettingsStack/settings-test.tsx
- src/screens/settings-developer-tools.tsx
- src/services/json-rpc-middleware/json-rpc-methods-handlers.ts
- src/services/sign-json-rpc-request.ts
Fixes #
- HQM-420 encrypted_data_not_found
> fix(HQM-420): encrypted_data_not_found

- src/components/bottom-popups/popup-backup-notification/backup-notification.tsx
- src/components/bottom-popups/popup-notification-news/popup-notification-news.tsx
- src/components/bottom-popups/popup-notification/notification-popup.tsx
- src/components/bottom-popups/popup-track-activity/popup-track-activity.tsx
- src/components/home-earn.tsx
- src/components/home-governance/voting-card/voting-card-active.tsx
- src/components/home-governance/voting-card/voting-card-completed.tsx
- src/components/top-tab-navigator-large.tsx
- src/components/wallet-card/wallet-card.tsx
- src/components/wallet-create.tsx
- src/components/web3-browser/web3-browser-action-menu.tsx
- src/variables/shadows.ts
> feat(HQM-417): add shadow preset

- src/components/transaction-sum/transaction-sum.tsx
> fix(HQM-384): error name

- src/components/popup/dismiss-popup-button.tsx
- src/event-actions/on-push-notification.ts
- src/helpers/get-news-detail-title.tsx
- src/route-types.ts
- src/screens/HomeStack/index.tsx
- src/types.ts
> fix(HQM-376): Update news navigation

- src/helpers/provider-instance.ts
- src/screens/HomeStack/BackupStack/backup-create.tsx
- src/screens/HomeStack/BackupStack/backup-verify.tsx
- src/screens/HomeStack/GovernanceStack/ProposalDepositStack/proposal-deposit-preview.tsx
- src/screens/HomeStack/HomeEarnStack/home-staking.tsx
- src/screens/HomeStack/HomeEarnStack/staking-info.tsx
- src/screens/HomeStack/StakingDelegateStack/staking-delegate-preview.tsx
- src/screens/HomeStack/StakingUndelegateStack/staking-undelegate-preview.tsx
- src/screens/HomeStack/TransactionStack/transaction-confirmation.tsx
- src/screens/HomeStack/TransactionStack/transaction-nft-confirmation.tsx
- src/services/json-rpc-middleware/json-rpc-methods-handlers.ts
- src/services/sign-json-rpc-request.ts
Fixes #
- remove wallet provider cache
> fix: remove wallet provider cache

- src/contexts/app.ts
Fixes #
- allow developer mode on mainnet
> feat: allow developer mode on mainnet

- src/components/stories/story-view/components/story-list.tsx
- src/components/stories/story-view/components/story-overlay.tsx
- src/helpers/url.ts
- src/types.ts
- src/widgets/banner-widget/index.tsx
> feat(HQM-422): handle target prop

- src/components/stories/story-view/components/story-container.tsx
> feat: video duration support

- src/components/bottom-popups/popup-notification-news/popup-notification-news.tsx
- src/components/bottom-popups/popup-notification/notification-popup.tsx
- src/components/bottom-popups/popup-track-activity/popup-track-activity.tsx
- src/components/create-agreement/create-agreement.tsx
- src/components/finish.tsx
- src/components/ledger-agreement/ledger-agreement.tsx
- src/components/ledger-verify/ledger-verify.tsx
- src/components/modals/ledger-attention.tsx
- src/components/onboarding-track-user-activity/onboarding-track-user-activity.tsx
- src/components/raffle-reward.tsx
- src/components/restore-agreement/restore-agreement.tsx
- src/components/sss-migrate-agreement/sss-migrate-agreement.tsx
- src/components/transaction-ledger/transaction-ledger.tsx
- src/components/ui/raffle-block.tsx
- src/components/wallet-protection.tsx
> fix: lottie animation size

- src/components/stories/story-view/components/story-container.tsx
- src/components/stories/story-view/components/story-header.tsx
- src/components/stories/story-view/components/story-overlay.tsx
- src/services/event-tracker.ts
- src/types.ts
> feat(HQM-425): stories analytics

- src/components/stories/story-view/components/story-container.tsx
- src/components/stories/story-view/components/story-header.tsx
- src/components/stories/story-view/components/story-list.tsx
- src/components/stories/story-view/components/story-overlay.tsx
- src/services/event-tracker.ts
> feat: add current story id to analytic events

- src/components/stories/story-view/components/story-overlay.tsx
> fix(HQM-426): markup render

- src/components/finish.tsx
- src/components/signin-networks/signin-networks.tsx
- src/components/signup-networks/signup-networks.tsx
- src/components/sss-migrate-networks/sss-migrate-networks.tsx
> fix: animation size

- src/helpers/provider-instance.ts
- src/services/event-tracker.ts
- src/types.ts
Fixes #
- provider sign events
> feat: provider sign events

- src/components/modals/modal-wrapper.tsx
- src/screens/HomeStack/home.tsx
> fix(HQM-428): sss cloud share modal

- index.js
- src/contexts/app.ts
- src/event-actions/on-app-started.ts
- src/helpers/provider-instance.ts
- src/services/cosmos.ts
- src/services/event-tracker.ts
- src/types.ts
> fix: marketing events

- index.js
- src/app.tsx
- src/helpers/provider-instance.ts
- src/services/cosmos.ts
- src/services/event-tracker.ts
- src/types.ts
Fixes #
- network id for tx events
> feat: network id for tx events

- src/helpers/provider-instance.ts
Fixes #
- hqm-430 provider wrapper issue
> fix(hqm-430): provider wrapper issue

- patches/react-native-encrypted-storage+4.0.3.patch
Fixes #
- parsing incorrect JSON for react-native-encrypted-storage
> fix(patch): parsing incorrect JSON for react-native-encrypted-storage

- package.json
This reverts commit 7ded52bab0c9051af38c724d9f8e6b9d56722bee.
Fixes #
-
-
-
> fix: app version

- src/components/modals/wallets-bottom-sheet.tsx
- src/components/settings/settings-account-detail/settings-account-detail.tsx
- src/components/ui/card.tsx
- src/components/ui/walletCard.tsx
- src/components/wallet-card/balance-info-details.tsx
- src/components/wallet-card/card-name.tsx
- src/components/wallet-card/wallet-card.tsx
- src/components/web3-browser/web3-browser-action-menu.tsx
> fix(HQM-347): styles

- android/app/build.gradle
- android/build.gradle
- ios/Podfile.lock
- package.json
- src/components/settings-language.tsx
- src/components/wallet-card/wallet-card.tsx
- src/models/socket.ts
- src/models/stories.ts
- yarn.lock
> fix: android cache crash

- src/components/settings-language.tsx
- src/components/wallet-card/wallet-card.tsx
- src/models/socket.ts
> fix: Small UI fixes

- src/helpers/get-app-info.ts
> feat: add buildNumber, currency and locale

- src/components/popup-header.tsx
- src/components/ui/provider-menu.tsx
- src/screens/HomeStack/HomeFeedStack/index.tsx
> feat(HQM-34): add provider selector on homepage

- ios/services/Cloud/Cloud.swift
> feat(HQM-442): create HAQQ Backup folder

- src/screens/HomeStack/home.tsx
> feat: add mnemonic share verification

- src/components/modals/pin.tsx
- src/contexts/app.ts
- src/helpers/modal.ts
- src/helpers/secure-pin-utils.ts
- src/i18n.ts
- src/screens/HomeStack/SettingsStack/settings-test.tsx
> feat(HQM-444): add pin backup flow

- src/contexts/app.ts
> feat: set old biometry state when keychain is restored

- src/components/captcha/captcha.tsx
- src/services/backend.ts
- src/services/remote-config/remote-config-default-values.ts
- src/services/remote-config/remote-config-types.ts
> feat(HQM-387): add contests_url and local_captcha_url

- src/contexts/app.ts
- src/screens/HomeStack/SettingsStack/settings-test.tsx
> fix: biometry restore

- src/components/locked-tokens.tsx
- src/components/nft-collection-details.tsx
- src/components/settings-accounts.tsx
- src/components/settings/settings-currency/settings-currency.tsx
- src/components/wallet-card/balance-info-total.tsx
- src/components/web3-browser/web3-browser-action-menu.tsx
- src/screens/HomeStack/NftStack/components/nft-item-details/nft-item-details.tsx
- src/screens/HomeStack/SettingsStack/settings-test.tsx
- src/screens/settings-developer-tools.tsx
> fix(HQM-447 HQM-448): rtl ui

- src/components/web3-browser/web3-browser-action-menu.tsx
> fix: browser action button

- src/components/web3-browser/web3-browser-action-menu.tsx
- src/screens/WelcomeStack/SignUpStack/signup-network-exists.tsx
> fix: browser action menu

- .github/workflows/distribute-ios.yml
- .github/workflows/e2e_ios.yml
> chore: update macos runner

- .github/workflows/distribute-ios.yml
Fixes #
-  iOS CI update ruby version
> chore: iOS CI update ruby version

- src/models/contracts.ts
- src/types.ts
Fixes #
-  lazy fetch contract data
> feat: lazy fetch contract data

- src/services/event-tracker.ts
- src/types.ts
- src/widgets/ad-widget/index.tsx
- src/widgets/banner-widget/index.tsx
Fixes #
- banner clicked event
> feat: banner clicked event

- src/services/eth-network/eth-network.ts
- src/services/eth-network/types.ts
> fix: erc20 fee calculations

- src/components/image-wrapper.tsx
- src/components/nft-viewer/nft-viewer-item-preview-small.tsx
- src/components/nft-viewer/nft-viewer-section-header.tsx
- src/components/transaction-confirmation/transaction-confirmation.tsx
- src/components/transaction-nft-confirmation.tsx
- src/components/transaction-nft-finish.tsx
- src/components/transaction-sum/transaction-sum.tsx
- src/components/wallet-connect-app-row.tsx
- src/components/wallet-connect-approval.tsx
> feat: image caching

- src/components/image-wrapper.tsx
> fix: image cache

- src/components/transaction-confirmation/transaction-confirmation.tsx
- src/components/transaction-finish.tsx
- src/components/transaction-nft-confirmation.tsx
- src/components/transaction-nft-finish.tsx
- src/models/fee/fee.ts
- src/models/fee/fee.types.ts
- src/models/fee/index.ts
- src/route-types.ts
- src/screens/HomeStack/TransactionStack/fee-settings.tsx
- src/screens/HomeStack/TransactionStack/transaction-confirmation.tsx
- src/screens/HomeStack/TransactionStack/transaction-finish.tsx
- src/screens/HomeStack/TransactionStack/transaction-nft-confirmation.tsx
- src/screens/HomeStack/TransactionStack/transaction-nft-finish.tsx
- src/services/eth-network/eth-network.ts
- src/services/eth-network/types.ts
> feat: Fee settings for NFT screen

- src/screens/HomeStack/JsonRpcSignPopupStack/json-rpc-sign-screen.tsx
> fix: json-rpc-sign-reject event

- src/components/json-rpc-transaction-info.tsx
- src/screens/HomeStack/JsonRpcSignPopupStack/json-rpc-sign-screen.tsx
Fixes #
- json rpc sign contract attention
> fix: json rpc sign contract attention

- src/models/fee/fee.ts
- src/screens/HomeStack/TransactionStack/fee-settings.tsx
> fix: disable/enable reset button based on user input

- src/components/transaction-finish.tsx
- src/route-types.ts
- src/screens/HomeStack/TransactionStack/transaction-finish.tsx
- src/screens/SwapStack/swap-screen.tsx
Fixes #
- swap transaction finish fixed explorer link and hide contact button
> fix: swap transaction finish

- .github/workflows/distribute-ios.yml
- .github/workflows/e2e_ios.yml
Fixes #
- enable mac-mini runner
> chore: enable mac-mini runner

- src/hooks/use-sum-amount.ts
- src/screens/SwapStack/swap-screen.tsx
Fixes #
- estimate swap on input
> feat: estimate swap on input

- src/models/fee/fee.ts
- src/screens/HomeStack/TransactionStack/fee-settings.tsx
> fix: Prevent unexpected fee restore for gasLimit and maxBaseFee

- src/screens/HomeStack/TransactionStack/fee-settings.tsx
> fix: Change keyboardType to numeric for fee settings

- src/components/image-wrapper.tsx
- src/components/nft-collection-details.tsx
- src/components/nft-viewer/nft-viewer-item-preview-large.tsx
- src/components/nft-viewer/nft-viewer-section-header.tsx
- src/components/transaction-nft-confirmation.tsx
- src/components/transaction-nft-finish.tsx
- src/hooks/nft/use-nft-collection-image.ts
- src/screens/HomeStack/NftStack/components/nft-item-details/nft-item-details.tsx
> feat: nft svg images

- src/components/modals/view-error-details.tsx
- src/helpers/check-app-version.ts
- src/screens/HomeStack/SettingsStack/settings-notification-screen.tsx
- src/services/remote-config/remote-config-default-values.ts
- src/services/remote-config/remote-config-types.ts
- [HQM-470](https://linear.app/haqq/issue/HQM-470/notification-permission-is-not-available-in-system-settings)
- [HQM-269](https://linear.app/haqq/issue/HQM-269/please-update-app-info)
-
> fix: push notification permissions fix

- src/screens/SwapStack/swap-screen.tsx
Fixes #
-  swap finish tx hash
> fix: swap finish tx hash

- src/components/home-settings/home-settings.tsx
- src/screens/settings-developer-tools.tsx
Fixes #
- HQM-473:  move language button to developer tools
> feat(HQM-473): move language button to developer tools

- package.json
- yarn.lock
Fixes #
- format-number-with-subscript-zeros lib
> fix: format-number-with-subscript-zeros

- src/screens/SwapStack/swap-screen.tsx
Fixes #
- swap token list & keyboard hide
> fix: swap token list & keyboard hide

- src/models/fee/fee.ts
- src/route-types.ts
- src/screens/HomeStack/JsonRpcSignPopupStack/json-rpc-sign-screen.tsx
- src/screens/SwapStack/swap-screen.tsx
- src/types.ts
> fix: save fee when interacting with swap

- src/hooks/use-sum-amount.ts
- src/screens/HomeStack/TransactionStack/fee-settings.tsx
Fixes #
- fee settings input validation
> fix: fee settings input validation

- src/components/transaction-select-crypto/transaction-select-crypto.tsx
- src/hooks/use-sum-amount.ts
- src/screens/HomeStack/TransactionStack/fee-settings.tsx
> fix(HQM-476): Fix useSumAmount initAmount calculations

- package.json
> chore: Version up to 1.8.1

- src/components/finish.tsx
> fix: onboarding finish screen UI for ipad

- package.json
- src/components/bottom-popups/popup-backup-sss-suggestion/backup-sss-suggestion.tsx
- src/components/transaction-sum/transaction-sum.tsx
- src/components/ui/sum-block.tsx
- src/event-actions/on-app-backup.ts
- src/route-types.ts
- src/screens/HomeStack/ManageAccountsStack/settings-account-detail.tsx
- src/screens/HomeStack/TransactionStack/transaction-confirmation.tsx
- src/screens/HomeStack/TransactionStack/transaction-finish.tsx
Fixes #
- [HQM-453](https://linear.app/haqq/issue/HQM-453/social-login-popup-does-not-appear)
- [HQM-468](https://linear.app/haqq/issue/HQM-468/incorrect-address-dispayed-on-transaction-completed-screen)
- [HQM-478](https://linear.app/haqq/issue/HQM-478/incorrect-fiat-estimation-on-send-screen-for-tokens)
> feat: fix: Release 1.8.2 features

- src/components/swap/estimated-value.tsx
- src/components/swap/swap.tsx
- src/screens/SwapStack/swap-screen.tsx
> fix(HQM-469): Update swap screen layout

- src/components/ui/sum-block.tsx
> fix: ISLM to fiat calculations

- android/build.gradle
> chore: Update android SDK to meet google play policies

- src/components/modals/error-modal.tsx
- src/types.ts
> fix(HW-414): Add close button to error modals

- src/contexts/app.ts
- src/models/provider/provider.ts
- src/services/backend/backend.ts
Fixes #
-  fix default provider value
> fix(HW-534): fix default provider value

- index.js
- src/models/language.ts
> feat(HW-438): Use system language by default

- src/components/ui/provider-menu.tsx
- src/contexts/app.ts
- src/debug-vars.ts
- src/models/tokens.ts
- src/services/remote-config/remote-config-default-values.ts
- src/services/remote-config/remote-config-types.ts
Fixes #
- refactor(HW-521): network providers
> refactor(HW-521): network providers

- src/models/language.ts
> fix: Crash when system language is unsupported

- src/hooks/use-wallets-balance.ts
> fix: Update balances when denom changed

- src/components/transaction-confirmation/transaction-confirmation.tsx
- src/helpers/indexer-transaction-utils.ts
- src/helpers/whitelist.ts
- src/models/contracts.ts
- src/models/provider/provider.ts
- src/models/tokens.ts
- src/screens/SwapStack/swap-screen.tsx
- src/services/__tests__/balance.test.ts
- src/services/balance.ts
- src/variables/common.ts
- src/widgets/transactions-short-widget/index.tsx
Fixes #
- remove hardcoded constants ISLM, aISLM, WEI
> feat(HW-565): remove hardcoded constants ISLM, aISLM, WEI

- src/contexts/app.ts
Fixes #
- providers first init
> fix: providers first init

- src/models/provider/provider.ts
- src/models/tokens.ts
- src/services/backend/backend.types.ts
> refactor: provider coin name

- ios/Podfile.lock
- ios/haqq.xcodeproj/project.pbxproj
- src/components/modals/providers-bottom-sheet.tsx
- src/components/ui/text-field.tsx
- yarn.lock
> feat(HW-522): Add search field to providers action sheet

- src/contexts/app.ts
- src/event-actions/on-provider-changed.ts
- src/models/provider/index.ts
- src/models/provider/provider-config.ts
- src/services/indexer/indexer.ts
- src/services/indexer/indexer.types.ts
- src/widgets/index.tsx
> feat(HW-573): Fetch provider config

- src/components/account-info/account-info.tsx
- src/components/total-value-info/total-value-info.tsx
- src/hooks/nft/index.ts
- src/hooks/nft/use-show-nft.tsx
- src/widgets/nft-widget/index.tsx
> feat(HW-571): Show NFT only when enabled by provider config

- src/event-actions/on-wallets-balance-check.ts
- src/models/currencies.ts
- src/services/indexer/indexer.ts
> feat(HW-577): Optimize indexer availability checks

- src/event-actions/on-wallets-balance-check.ts
- src/types.ts
Fixes #
- Inconsistent Key Formats in JSON Responses for Balances
> fix(HW-581): Inconsistent Key Formats in JSON Responses for Balances

- src/contexts/app.ts
- src/event-actions/on-provider-changed.ts
- src/event-actions/on-transaction-status-load.ts
- src/event-actions/on-transactions-load.ts
- src/event-actions/on-wallets-balance-check.ts
- src/helpers/whitelist.ts
- src/models/currencies.ts
- src/models/nft/nft-store.ts
- src/models/tokens.ts
- src/models/transaction.ts
- src/services/balance.ts
- src/services/indexer/indexer.ts
> fix: provider changing

- src/components/transaction-finish.tsx
- src/components/transaction-nft-finish.tsx
- src/helpers/url.ts
- src/models/provider/provider.ts
- src/screens/HomeStack/HomeFeedStack/transaction-detail.tsx
> fix: HW-527 explorer links

- src/components/modals/providers-bottom-sheet.tsx
- src/contexts/app.ts
- src/event-actions/index.ts
- src/event-actions/on-provider-changed.ts
- src/event-actions/on-sync-app-balances.ts
- src/models/tokens.ts
- src/models/transaction.ts
- src/services/indexer/indexer.ts
> fix: multichain providers

- src/screens/HomeStack/TransactionStack/fee-settings.tsx
> fix(HW-563): Custom fee fix

- src/services/json-rpc-middleware/json-rpc-methods-handlers.ts
Fixes #
- fixed web3 browser eth get block
> fix: web3 browser eth get block

- src/debug-vars.ts
- src/models/tokens.ts
> fix: erc20

- src/models/contracts.ts
- src/models/tokens.ts
- src/screens/HomeStack/TransactionStack/transaction-sum.tsx
- src/services/eth-network/erc20.ts
Fixes #
-  providers ERC20 contract data
> fix: providers ERC20 contract data

- src/components/transaction-sum/transaction-sum.tsx
- src/components/ui/sum-block.tsx
- src/helpers/short-address.ts
> fix: tx sum screen

- src/components/transaction-sum/transaction-sum.tsx
- src/components/ui/sum-block.tsx
- src/hooks/use-sum-amount.ts
- src/services/balance.ts
Fixes #
-  transaction sum token decimals and MAX button
> fix: transaction sum token decimals and MAX button

- .github/workflows/patch-build-versions.yml
Fixes #
- iOS patch build lane
> fix: ios patch build lane

- src/components/transaction-confirmation/transaction-confirmation.tsx
> fix(HW-604): Transaction amount error

- src/components/modals/providers-bottom-sheet.tsx
Fixes #
- can't change network in web3 browser
> fix(HW-606): can't change network in web3 browser

- src/components/locked-tokens.tsx
- src/components/total-value-info/total-value-info-header.tsx
- src/components/wallet-card/balance-info-total.tsx
- src/services/balance.ts
> fix(HW-591): fix balances

- src/components/swap/swap.tsx
- src/screens/SwapStack/swap-screen.tsx
- src/services/indexer/indexer.types.ts
Fixes #
- sushi swap infinty loader on Ethereum mainnet
> fix(HW-613): sushi swap infinity loader on Ethereum mainnet

- src/models/tokens.ts
> revert: fetchTokens

- .github/workflows/distribute-android.yml
- .github/workflows/distribute-ios.yml
- .github/workflows/distribute.yml
- .github/workflows/e2e.yml
- .github/workflows/e2e_android.yml
- .github/workflows/e2e_ios.yml
- .github/workflows/generate-release-notes.yml
- .github/workflows/main.yml
- .github/workflows/merged-action.yml
- src/components/total-value-info/total-value-info.tsx
- src/helpers/is-feature-enabled.ts
- src/hooks/nft/use-show-nft.tsx
- src/types/env.d.ts
> chore: Remove sss nft feature flags

- src/components/settings/settings-account-detail/settings-account-detail.tsx
- src/components/ui/copy-menu.tsx
> feat(HW-582): Hide bech32

- ios/Podfile.lock
- src/screens/HomeStack/TransactionStack/fee-settings.tsx
- src/services/eth-network/eth-network.ts
- src/services/eth-network/types.ts
> fix(HW-594): Custom fee calculations for decimals

- src/services/event-tracker.ts
> fix: posthog id

- src/event-actions/on-provider-changed.ts
- src/event-actions/on-wallets-balance-check.ts
- src/models/currencies.ts
- src/models/provider/provider.ts
- src/models/tokens.ts
- src/services/indexer/indexer.ts
- src/utils.ts
> feat: app optimization

- src/debug-vars.ts
- src/models/tokens.ts
Fixes #
- updated token parsing logic
> refactor: updated token parsing logic

- src/components/transaction-confirmation/transaction-confirmation.tsx
- src/components/transaction-finish.tsx
- src/components/transaction-nft-confirmation.tsx
- src/components/transaction-nft-finish.tsx
- src/screens/HomeStack/TransactionStack/transaction-confirmation.tsx
- src/screens/HomeStack/TransactionStack/transaction-nft-confirmation.tsx
Fixes #
- make addresses fields copy-able
> feat(HW-609): make addresses fields copy-able

- src/components/json-rpc-sign/json-rpc-common-transaction.tsx
- src/components/json-rpc-sign/json-rpc-sign.tsx
- src/components/json-rpc-sign/json-rpc-swap-transaction.tsx
- src/components/json-rpc-sign/json-rpc-transaction-info.tsx
- src/components/swap/swap-route-path-icons.tsx
- src/components/swap/swap.tsx
- src/models/provider/provider-config.ts
- src/models/tokens.ts
- src/screens/SwapStack/swap-screen.tsx
- src/services/backend/backend.types.ts
- src/services/indexer/indexer.types.ts
Fixes #
- improve swap UI and fix crash
> fix(NativeSwap): improve swap UI and fix crash

- src/widgets/index.tsx
- src/widgets/nft-widget/index.tsx
> fix: Hide nft widget if no nfts

- src/components/account-detail.tsx
- src/components/settings/settings-account-detail/settings-account-detail.tsx
- src/components/swap/swap.tsx
- src/components/ui/copy-menu.tsx
- src/event-actions/on-provider-changed.ts
- src/hooks/nft/use-show-nft.tsx
- src/models/provider/provider-config-model.ts
- src/models/provider/provider-config.ts
- src/models/provider/provider.ts
- src/screens/HomeStack/NftStack/nft-item-details.tsx
- src/screens/SwapStack/swap-screen.tsx
- src/services/indexer/indexer.types.ts
- src/types.ts
Fixes #
- refactor explorer urls
> refactor(HW-630): refactor explorer urls

- src/i18n.ts
- src/types.ts
- src/variables/common.ts
> chore: disable unsupported langs

- src/components/ui/info-block-amount.tsx
- src/components/ui/sum-block.tsx
> fix: sum block layout

- src/contexts/app.ts
- src/event-actions/on-provider-changed.ts
- src/events.ts
- src/hooks/use-wallets-balance.ts
- src/services/balance.ts
- src/variables/common.ts
Fixes #
- changing native symbol
> fix: changing native symbol

- src/components/modals/wallets-bottom-sheet.tsx
- src/components/wallet-row-variant-3.tsx
- src/components/wallet-row-variant-4.tsx
- src/components/wallet-row-variant-5.tsx
- src/components/wallet-row.tsx
- src/helpers/await-for-wallet.ts
- src/screens/HomeStack/BrowserStack/web3-browser.tsx
- src/services/json-rpc-middleware/json-rpc-methods-handlers.ts
- src/types.ts
> feat: Add hide balance option

- src/components/json-rpc-sign/json-rpc-swap-transaction.tsx
- src/components/json-rpc-sign/json-rpc-transaction-info.tsx
- src/components/swap/swap.tsx
- src/screens/SwapStack/swap-screen.tsx
Fixes #
- fixed swaps tokens validation
> fix: swaps tokens validation

- src/event-actions/on-provider-changed.ts
- src/helpers/get-app-info.ts
Fixes #
- fix: fetch widgets when chain changed
> fix: fetch widgets when chain changed

- src/components/json-rpc-sign/json-rpc-common-transaction.tsx
- src/components/json-rpc-sign/json-rpc-swap-transaction.tsx
- src/helpers/indexer-transaction-utils.ts
- src/models/tokens.ts
Fixes #
- handling unknown tokens
> fix: handling unknown tokens

- src/components/account-detail.tsx
- src/components/modals/details-qr.tsx
> fix: add translation keys for recieve warning

- src/components/home-settings/home-settings.tsx
Fixes #
- hw-637: enable-language-menu-in-settings
> feat(hw-637): enable-language-menu-in-settings

- src/components/home-settings/settings-button.tsx
- src/components/ui/data-content.tsx
- src/components/wallet-row-variant-5.tsx
> fix(HW-634): DataContent has wrong subtitle styles

- package.json
> chore: Up version to 1.9.1

- src/components/locked-tokens.tsx
- src/components/notification-settings-no-permission.tsx
- src/components/settings-about-button.tsx
- src/components/settings/settings-account-detail/settings-account-detail.tsx
- src/components/total-value-info/total-value-info-header.tsx
- src/components/transaction-confirmation/transaction-confirmation.tsx
- src/components/ui/button.tsx
- src/components/ui/sum-block.tsx
- src/components/wallet-card/card-name.tsx
- src/components/web3-browser/web3-browser-action-menu.tsx
> fix(hw-472): rtl ui issues

- src/helpers/get-wallet-title.ts
- src/models/language.ts
- src/screens/WelcomeStack/SignUpStack/index.tsx
- src/screens/WelcomeStack/SignUpStack/signup-networks.tsx
> fix(HW-651): Missing translation on create wallet screen

- android/app/build.gradle
- android/app/src/main/java/com/haqq/wallet/MainActivity.kt
- android/app/src/main/java/com/haqq/wallet/MainApplication.kt
- android/settings.gradle
- index.js
- ios/AppDelegate.swift
- patches/react-native-restart+0.0.27.patch
- src/services/backend/backend.ts
- src/utils.ts
> fix(HW-642): fix rtl support

- src/components/keystone/keystone-camera-permission.tsx
- src/components/ledger-bluetooth/ledger-bluetooth.tsx
- src/screens/DeviceStack/KeystoneStack/keystone-finish.tsx
- src/screens/DeviceStack/LedgerStack/ledger-bluetooth.tsx
- src/screens/DeviceStack/LedgerStack/ledger-finish.tsx
Fixes #
- HW-500: visual bugs p4
> fix(HW-500): visual bugs p4

- src/helpers/get-app-headers.ts
> feat(HW-659): Add Accept-Language

- docs/sss.md
- src/services/eth-network/eth-network.ts
- src/services/wallet-connect.ts
> chore: Fix some typos in comments

- src/screens/WelcomeStack/SignInStack/signin-networks.tsx
- src/screens/WelcomeStack/SignUpStack/signup-agreement.tsx
Fixes #
-  fix hardware button navigation
> fix(HW-667): 'connect hardware wallet' button navigation

- index.js
- src/i18n.ts
Fixes #
-  improve change language functionality
> fix(HW-665): improve change language functionality

- src/screens/SwapStack/swap-screen.tsx
Fixes #
- fix Arabic. Zero values in Receive field on Swap
> fix(HW-684): Zero values in Receive field on Swap

- src/components/json-rpc-sign/json-rpc-sign.tsx
- src/components/json-rpc-sign/json-rpc-swap-transaction.tsx
- src/components/json-rpc-sign/json-rpc-transaction-info.tsx
- src/components/swap/swap-route-path-icons.tsx
- src/helpers/whitelist.ts
- src/screens/HomeStack/JsonRpcSignPopupStack/json-rpc-sign-screen.tsx
- src/types.ts
> fix: Contracts fetching and caching

- src/contexts/app.ts
- src/models/currencies.ts
> fix: remove testnet currencies from all networks balances

- yarn.lock
> restore yarn lock

- package.json
- src/components/transaction-list/transaction-list.tsx
- src/events.ts
- src/hooks/use-wallets-balance.ts
- src/models/provider/provider.ts
- src/models/transaction.ts
- src/screens/HomeStack/ProvidersStack/settings-provider-edit.tsx
Fixes #
- [Endless animation on Network change](https://linear.app/haqq/issue/HW-650/endless-animation-on-network-change)
- [Duplicate entries in Transaction history](https://linear.app/haqq/issue/HW-735/duplicate-entries-in-transaction-history)
> Release 1.9.3

- index.js
- src/modifiers/index.ts
- src/modifiers/json-rpc-provider.modifier.ts
> chore: index.js sugar

- src/components/top-tab-navigator.tsx
- src/components/total-value-info/total-value-info.tsx
- src/hooks/use-wallets-balance.ts
> fix(HW-767): Fix total-value-screen

- src/components/json-rpc-sign/json-rpc-swap-transaction.tsx
- src/components/json-rpc-sign/json-rpc-transaction-info.tsx
- src/components/swap/swap.tsx
- src/models/tokens.ts
- src/screens/SwapStack/swap-screen.tsx
> fix: swap tokens list

- src/components/swap/swap-finish.tsx
- src/screens/HomeStack/JsonRpcSignPopupStack/json-rpc-sign-screen.tsx
- src/screens/SwapStack/swap-finish-screen.tsx
- src/screens/SwapStack/swap-screen.tsx
- src/services/event-tracker.ts
- src/types.ts
> feat(HW-774): swap events

- Gemfile
> chore: fix cocoapods rule

- src/screens/SwapStack/swap-screen.tsx
> fix: swap estimate rate

- src/models/provider/provider-config.model.ts
- src/screens/SwapStack/swap-screen.tsx
- src/services/indexer/indexer.types.ts
Fixes #
- add feature flag `enable_unwrapWETH9_call`
> feat: add feature flag `enable_unwrapWETH9_call`

- src/components/wallet-card/card-name.tsx
- src/screens/settings-developer-tools.tsx
Fixes #
- Transaction snippets for raw sign request
- Show HD path
> feat: add features for developer

- src/components/json-rpc-sign/json-rpc-swap-transaction.tsx
- src/components/json-rpc-sign/json-rpc-transaction-info.tsx
- src/screens/SwapStack/swap-screen.tsx
Fixes #
- unwrap wISLM to ISLM after swap
- fix UI
> fix: unwrap wISLM to ISLM after swap

- src/components/account-info/account-info-header.tsx
- src/components/json-rpc-sign/json-rpc-sign-info.tsx
- src/components/json-rpc-sign/json-rpc-sign.tsx
- src/components/settings-accounts.tsx
- src/components/settings/settings-account-detail/settings-account-detail.tsx
- src/components/swap/swap.tsx
- src/components/transaction-account.tsx
- src/components/transaction-address.tsx
- src/components/wallet-connect-application-details.tsx
- src/components/wallet-connect-approval.tsx
- src/components/wallet-connect-wallet-list.tsx
- src/components/wallet-row-variant-1.tsx
- src/components/wallet-row-variant-2.tsx
- src/components/wallet-row-variant-3.tsx
- src/components/wallet-row-variant-4.tsx
- src/components/wallet-row-variant-5.tsx
- src/components/wallet-row.tsx
- src/components/wallet-selector.tsx
- src/helpers/await-for-wallet.ts
- src/route-types.ts
- src/screens/HomeStack/WalletConnectApprovalStack/wallet-connect-approval.tsx
- src/screens/HomeStack/WalletConnectStack/wallet-connect-wallet-list.tsx
- src/types.ts
> chore: Update visible addresses to providerSpecificAddress

- package.json
- src/components/wallet-card/wallet-card.tsx
- src/event-actions/on-app-started.ts
- src/helpers/address-utils.ts
- src/helpers/provider-instance/provider-event-tracker-wrapper.ts
- src/models/migration-wallets.ts
- src/models/wallet/wallet.model.ts
- src/models/wallet/wallet.store.ts
- src/screens/WelcomeStack/SignInStack/signin-store-wallet.tsx
- src/screens/WelcomeStack/SignUpStack/signup-store-wallet.tsx
- src/services/indexer/indexer.ts
- src/services/sign-json-rpc-request.ts
- yarn.lock
Fixes #
- show correct RX address
- migrate mnemonic wallets
- send correct TRX address to indexer
- some optimizations on app start up
> feat: migrate mnemonic wallets

- src/app.tsx
- src/components/modals/keystone/keystone-scanner.tsx
- src/debug-vars.ts
- src/screens/DeviceStack/KeystoneStack/index.tsx
- src/screens/DeviceStack/KeystoneStack/keystone-finish.tsx
- src/screens/DeviceStack/LedgerStack/index.tsx
- src/screens/DeviceStack/LedgerStack/ledger-finish.tsx
- src/screens/RootStack/index.tsx
- src/screens/WelcomeStack/SignInStack/signin-networks.tsx
- src/screens/WelcomeStack/SignUpStack/signup-agreement.tsx
- src/screens/WelcomeStack/index.tsx
> fix: react native navigation modals dont close

- src/services/provider-sss.ts
> fix(hw-806): fix sss wallets

- ios/Podfile.lock
- src/components/choose-account/choose-account-row.tsx
- src/components/json-rpc-sign/json-rpc-common-transaction.tsx
- src/components/transaction-address.tsx
- src/components/transaction-confirmation/transaction-confirmation.tsx
- src/components/ui/copy-menu.tsx
- src/debug-vars.ts
- src/helpers/address-utils.ts
- src/helpers/get-rpc-provider.ts
- src/helpers/get-wallets-from-provider.tsx
- src/helpers/safe-load-balances.ts
- src/helpers/secure-pin-utils.ts
- src/models/migration-wallets.ts
- src/models/wallet/wallet.store.ts
- src/route-types.ts
- src/screens/HomeStack/TransactionStack/transaction-address.tsx
- src/screens/HomeStack/TransactionStack/transaction-confirmation.tsx
- src/screens/HomeStack/TransactionStack/transaction-sum-address.tsx
- src/screens/HomeStack/index.tsx
- src/screens/WelcomeStack/SignInStack/signin-not-exists.tsx
- src/screens/WelcomeStack/SignUpStack/signup-store-wallet.tsx
- src/screens/choose-account-screen.tsx
- src/services/eth-network/eth-network.ts
- src/services/indexer/indexer.ts
> fix(hw-820): tron bug fixes for incorrect wallet address generation

- src/components/modals/copy-address-bottom-sheet.tsx
- src/components/modals/providers-bottom-sheet.tsx
- src/event-actions/on-wallet-connect-sign-transaction.ts
- src/models/provider/provider.ts
- src/screens/HomeStack/BrowserStack/web3-browser.tsx
- src/screens/SwapStack/swap-screen.tsx
- src/services/json-rpc-middleware/json-rpc-methods-handlers.ts
Fixes #
- Restrict WEB3 browser for TRON
> feat(HW-784): Restrict WEB3 browser for TRON

- .env.example
- .github/workflows/distribute-android.yml
- .github/workflows/distribute-ios.yml
- .github/workflows/e2e_android.yml
- .github/workflows/e2e_ios.yml
- .github/workflows/generate-release-notes.yml
- scripts/pull-locales.mjs
- src/components/ui/card-small.tsx
- src/event-actions/on-banner-gasdrop-create.ts
- src/services/airdrop.ts
- src/services/backend/backend.ts
- src/services/remote-config/remote-config-default-values.ts
- src/services/remote-config/remote-config.service.ts
- src/services/remote-config/remote-config.types.ts
- src/types/env.d.ts
- src/utils.ts
Fixes #
- move env variables to remote config
- update .env.exaple
- remove unused vars from .env
- update env.d.ts types
> feat(HW-833): move env variables to remote config

- src/components/transaction-list/transaction-row.tsx
- src/helpers/indexer-transaction-utils.ts
- src/types.ts
> feat(HW-697): Transaction list screen for TRON transactions

- assets/locales/ar/ar.json
- assets/locales/en/en.json
- assets/locales/id/id.json
- assets/locales/tr/tr.json
- src/ar.ts
- src/components/ui/hardware-wallet-button.tsx
- src/components/wallet-create.tsx
- src/components/welcome.tsx
- src/i18n.ts
> feat(HW-823): Hide hardware connect button for TRON

- src/services/remote-config/remote-config.service.ts
Fixes #
- crash on app startup
> fix(HW-849): crash on app startup

- package.json
- src/components/token-row.tsx
- src/components/token-viewer/token-viewer.tsx
- src/components/transaction-confirmation/transaction-confirmation.tsx
- src/helpers/address-utils.ts
- src/models/nft/nft-store.ts
- src/models/tokens.ts
- src/screens/HomeStack/TransactionStack/transaction-confirmation.tsx
- src/screens/HomeStack/TransactionStack/transaction-sum.tsx
- src/screens/choose-account-screen.tsx
- src/services/balance.ts
- src/services/eth-network/eth-network.ts
- src/services/indexer/indexer.ts
- src/services/remote-config/remote-config.service.ts
- src/services/tron-network/tron-network.ts
- yarn.lock
Fixes #
- HW-693 Support for viewing TRC-20 tokens balances
- HW-883 Fix addresses request
- HW-813 Support for send TRC-20 tokens
- HW-920 fee calculation for TRON
> feat: support TRC20 tokens for Tron

- src/components/account-info/account-info.tsx
- src/components/token-viewer/token-viewer.tsx
- src/components/transaction-list/transaction-list.tsx
> fix(HW-913): fix tokens list

- src/components/qr-scanner-button.tsx
- src/event-actions/on-deep-link.ts
> feat(HW-780): TRON support for scan QR codes

- src/components/json-rpc-sign/json-rpc-common-transaction.tsx
- src/components/json-rpc-sign/json-rpc-swap-transaction.tsx
- src/components/json-rpc-sign/json-rpc-transaction-info.tsx
- src/components/wallet-connect-application-details.tsx
- src/components/wallet-connect-approval.tsx
- src/components/wallet-connect-wallet-list.tsx
- src/event-actions/on-wallet-connect-sign-transaction.ts
- src/hooks/use-wallet-connect-accounts.ts
- src/screens/HomeStack/JsonRpcSignPopupStack/json-rpc-sign-screen.tsx
- src/screens/HomeStack/WalletConnectApprovalStack/wallet-connect-approval.tsx
- src/screens/HomeStack/WalletConnectStack/wallet-connect-wallet-list.tsx
- src/services/sign-json-rpc-request.ts
> fix: send EVM transaction while Tron is active

- src/components/token-viewer/token-viewer.tsx
- src/contexts/app.ts
- src/screens/settings-developer-tools.tsx
Fixes #
- show non-whitelisted tokens for dev mode
> feat: show non-whitelisted tokens for dev mode

- src/models/tokens.ts
- src/widgets/tokens-widget/index.tsx
- src/widgets/transactions-widget/transactions-widget.tsx
Fixes #
-  fetch ERC20 token contract info for transactions list when token balance is zero
> fix: fetch ERC20 token contract info for transactions list when token balance is zero

- src/components/home-feed.tsx
- src/event-actions/index.ts
- src/event-actions/on-app-logged-in.ts
- src/event-actions/on-transactions-load.ts
- src/event-actions/on-wallet-create.ts
- src/events.ts
- src/helpers/load-transactions.ts
- src/hooks/use-transaction-list.ts
- src/models/transaction.ts
Fixes #
- Too many transactions_by_timestamp requests on app start
> fix(HW-948): Too many transactions_by_timestamp requests on app start

- src/models/provider/provider.model.ts
- src/models/whitelist/whitelist.store.ts
- src/screens/HomeStack/JsonRpcSignPopupStack/json-rpc-sign-screen.tsx
Fixes #
- disable url whitelist for testnet chains
> feat(HW-944): disable url whitelist for testnet chains

- docs/inpage-bridge-web3.md
- src/hooks/use-webview-shared-props.tsx
Fixes #
-  inject app language to webview
> feat(HW-755): inject app language to webview

- src/components/transaction-nft-finish.tsx
- src/components/transaction-sum/transaction-sum.tsx
- src/hooks/use-transaction-list.ts
- src/models/tokens.ts
- src/screens/HomeStack/TransactionStack/transaction-sum.tsx
- src/widgets/tokens-widget/index.tsx
- src/widgets/tokens-widget/tokens-widget.tsx
Fixes #
- Crash on NFT Send Finish Screen
Resolved an issue causing the app to crash when navigating to the finish screen after sending an NFT.
- Transaction Amount and Fee Validation
Implemented validation to display an error message when the transaction amount is too low or if the fee is insufficient, improving the user experience and preventing transaction failures.
- Incorrect Token Widget Amount Display
Fixed a bug where token widget was displaying incorrect amounts, ensuring accurate token balance visibility across the app.
- Token Contract Data Caching
Improved caching mechanism for token contract data to reduce redundant data loading, resulting in smoother performance.
> fix: app crashes and ui bugs

- index.js
- src/helpers/get-mm-phishing-controller.ts
- src/models/banner.ts
- src/models/browser-permission.ts
- src/models/contact.ts
- src/models/currencies.ts
- src/models/error-handler.ts
- src/models/language.ts
- src/models/provider/provider-config.ts
- src/models/provider/provider.ts
- src/models/raffles.ts
- src/models/socket.ts
- src/models/stories.ts
- src/models/tokens.ts
- src/models/wallet/wallet.store.ts
- src/models/whitelist/whitelist.store.ts
> chore: Setup MMKV as default storage for persistance

- index.js
- src/event-actions/on-wallet-remove.ts
- src/screens/DeviceStack/KeystoneStack/keystone-accounts.tsx
- src/screens/WelcomeStack/SignInStack/signin-networks.tsx
- src/screens/choose-account-screen.tsx
Fixes #
- Block swipe down on Account import/create flow
> fix(HW-955): Block swipe down on Account import/create flow

- src/components/wallet-card/card-name.tsx
> fix: Card Wallet styles

- src/components/wallet-card/card-name.tsx
Fixes #
- fixed wallet card name
> fix: wallet card name

- ios/services/Cloud/Cloud.swift
- src/screens/WelcomeStack/SignInStack/signin-networks.tsx
> fix(SSS): google iOS login

- src/components/device-select.tsx
- src/components/keystone/keystone-camera-permission.tsx
- src/components/keystone/keystone-connection-steps.tsx
- src/screens/DeviceStack/KeystoneStack/keystone-accounts.tsx
- src/screens/WelcomeStack/SignInStack/signin-networks.tsx
- src/screens/choose-account-screen.tsx
Fixes #
- no wallets on import hardware wallet
> fix(HW-965): no wallets on import hardware wallet

- src/components/account-info/account-info-header.tsx
- src/components/ui/button.tsx
- src/components/wallet-card/card-buttons.tsx
- src/helpers/provider-instance/provider-instance.ts
- src/models/wallet/wallet.store.ts
- src/screens/HomeStack/JsonRpcSignPopupStack/json-rpc-sign-screen.tsx
- src/screens/HomeStack/NftStack/components/nft-item-details/nft-item-details.tsx
- src/screens/HomeStack/TransactionStack/index.tsx
- src/screens/settings-developer-tools.tsx
- src/screens/total-value-info.tsx
- src/types.ts
> feat(HW-967): watch only wallet

- src/components/settings/settings-account-detail/settings-account-detail.tsx
- src/components/wallet-card/protection-badge.tsx
> fix: wallet bage

- src/hooks/use-transaction-list.ts
> fix: Deep check for address list to prevent infinity transactions fetches

- package.json
- src/helpers/get-provider-for-new-wallet.ts
- src/screens/WelcomeStack/SignUpStack/signup-store-wallet.tsx
- yarn.lock
> fix: sss errors

- src/models/provider/provider-config.ts
- src/models/provider/provider.ts
> Restore storage for Provider and ProviderConfig

- src/models/provider/provider-config.ts
- src/models/provider/provider.ts
> chore: Setup provider cache to 3 hours

- src/components/token/token-row.tsx
- src/components/transaction-confirmation/transaction-confirmation.tsx
- src/components/wallet-card/protection-badge.tsx
- src/models/wallet/wallet.model.ts
- src/screens/HomeStack/HomeFeedStack/account-info.tsx
- src/screens/settings-developer-tools.tsx
- src/services/balance.ts
- src/services/provider-sss.ts
- src/services/tron-network/tron-network.ts
> fix: tron fee

- src/components/ui/text-field.tsx
Fixes #
-  incorrect keyboard behaviour
> fix(HW-994): incorrect keyboard behaviour

- src/screens/transaction-select-crypto.tsx
> feat: Placeholder while fetch tokens

- src/models/currencies.ts
- src/services/tron-network/tron-network.ts
Fixes #
-  trc20 fee estimations
- currency rate for tron
> fix(HW-995): trc20 fee estimations and currency rate for tron

- src/screens/transaction-select-crypto.tsx
> feat: Add more placeholders to tokens list

- src/components/transaction-sum/transaction-sum.tsx
- src/services/balance.ts
- src/services/tron-network/tron-network.ts
> fix: fee estimate warn

- src/app.tsx
- src/components/account-info/account-info-header.tsx
- src/components/account-info/account-info.tsx
- src/components/stacked-vested-tokens.tsx
- src/components/total-value-info/total-value-info-header.tsx
- src/components/wallet-card/balance-info-details.tsx
- src/components/wallet-card/balance-info-total.tsx
- src/components/wallet-card/card-name.tsx
- src/components/wallet-card/protection-badge.tsx
- src/components/wallet-card/wallet-card.tsx
- src/helpers/address-utils.ts
- src/models/tokens.ts
- src/models/wallet/wallet.store.ts
- src/screens/HomeStack/HomeFeedStack/account-info.tsx
- src/screens/HomeStack/SettingsStack/settings-test.tsx
- src/screens/HomeStack/index.tsx
- src/screens/network-logger.tsx
- src/screens/settings-developer-tools.tsx
> fix: balance placeholders

- src/components/bottom-sheet.tsx
- src/components/locked-tokens.tsx
- src/components/modals/modal-wrapper.tsx
- src/components/modals/providers-bottom-sheet.tsx
- src/components/total-value-info/total-value-info-header.tsx
- src/components/ui/provider-menu.tsx
- src/components/ui/walletCard.tsx
- src/components/wallet-card/card-buttons.tsx
- src/components/wallet-card/wallet-card.tsx
- src/helpers/modal.ts
- src/models/app/app.store.ts
- src/models/provider/provider.model.ts
- src/models/provider/provider.ts
- src/models/wallet/balance.model.ts
- src/models/wallet/wallet.store.ts
- src/screens/HomeStack/ReceiveStack/select-network-screen.tsx
- src/screens/HomeStack/SettingsStack/settings-test.tsx
- src/screens/modals-screen.tsx
- src/screens/settings-developer-tools.tsx
> fix: balance fetching

- src/components/modals/providers-bottom-sheet.tsx
- src/screens/HomeStack/ReceiveStack/select-network-screen.tsx
> fix: bottom sheet crash

- src/models/wallet/wallet.store.ts
- src/screens/HomeStack/in-app-browser.tsx
> fix(Tron): all-network show balance for unsupported wallets

- src/screens/HomeStack/TransactionStack/transaction-confirmation.tsx
> fix: Send TRON tokens at All Networks

- src/models/wallet/wallet.model.ts
- src/services/eth-network/eth-network.ts
> fix: Correct hdPath for TRON at All Networks

- src/components/account-info/account-info-header.tsx
- src/components/settings/settings-account-detail/settings-account-detail.tsx
- src/components/transaction-select-crypto/transaction-select-crypto.tsx
- src/components/wallet-card/card-name.tsx
- src/components/wallet-row-variant-5.tsx
- src/event-actions/on-banner-claim-airdrop.ts
- src/event-actions/on-staking-rewards.ts
- src/helpers/get-leading-account.ts
- src/models/migration-wallets.ts
- src/models/wallet/wallet.model.ts
- src/screens/HomeStack/GovernanceStack/ProposalDepositStack/proposal-deposit-preview.tsx
- src/screens/HomeStack/GovernanceStack/proposal.tsx
- src/screens/HomeStack/HomeEarnStack/staking-info.tsx
- src/screens/HomeStack/SettingsStack/settings-test.tsx
- src/screens/HomeStack/StakingDelegateStack/staking-delegate-form.tsx
- src/screens/HomeStack/StakingDelegateStack/staking-delegate-preview.tsx
- src/screens/HomeStack/StakingUndelegateStack/staking-undelegate-form.tsx
- src/screens/HomeStack/StakingUndelegateStack/staking-undelegate-preview.tsx
- src/screens/HomeStack/TransactionStack/transaction-address/transaction-address-wallet-list.tsx
- src/screens/HomeStack/TransactionStack/transaction-sum.tsx
- src/screens/WelcomeStack/SignInStack/signin-store-wallet.tsx
- src/screens/WelcomeStack/SignUpStack/signup-store-wallet.tsx
- src/services/eth-network/eth-network.ts
- src/services/json-rpc-middleware/json-rpc-methods-handlers.ts
> fix: getPath and TRON address

- assets/locales/ar/ar.json
- assets/locales/en/en.json
- assets/locales/id/id.json
- assets/locales/tr/tr.json
- src/ar.ts
- src/components/signin-networks/signin-networks.tsx
- src/i18n.ts
- src/route-types.ts
- src/screens/HomeStack/SssMigrate/sss-migrate-networks.tsx
- src/screens/WelcomeStack/SignUpStack/signup-networks.tsx
- src/services/provider-sss.ts
> fix: Update auth flow by new restore policy

- src/services/sign-json-rpc-request.ts
Fixes #
- fix web3 browser signing
> fix: web3 browser signing

- src/app.tsx
- src/models/app/app.store.ts
- src/screens/network-logger.tsx
- src/screens/settings-developer-tools.tsx
> feat: open network logger from DevSettings

- src/components/swap/estimated-value.tsx
- src/components/swap/swap-input.tsx
- src/components/ui/text-field.tsx
- src/screens/SwapStack/swap-screen.tsx
- src/services/balance.ts
- src/services/sign-json-rpc-request.ts
Fixes #
- zero token balances on swap
> fix(HW-1035): zero token balances on swap

- src/app.tsx
> fix(HW-1035): Zero token balances on Swap (#2255)

- src/components/json-rpc-sign/json-rpc-common-transaction.tsx
- src/models/contract/contract.store.ts
- src/models/contract/contract.types.ts
- src/models/tokens.ts
- src/screens/SwapStack/swap-screen.tsx
- src/types.ts
> fix(HW-1050): TRC20 tokens are not displayed

- package.json
- scripts/format-network-logs.mjs
Fixes #
- add network logs formatter script
> chore: add network logs formatter script

- .github/workflows/main.yml
- .github/workflows/update-version.yml
- package.json
> fix runner tag
