src/screens/home-feed.tsx
Fix scroll on main page while has no operations
https://github.com/haqq-network/haqq-wallet/issues/86
=> fix #86: markup on main screen

src/components/modals/pin.tsx, src/components/pin.tsx, src/contexts/app.ts, src/models/index.ts, src/models/user.ts, src/variables.ts
=> prevent pin bruteforce

src/components/ui/textarea.tsx, src/models/user.ts, src/screens/create.tsx, src/screens/onboarding-biometry.tsx, src/screens/onboarding-repeat-pin.tsx, src/screens/onboarding-setup-pin.tsx, src/screens/restore.tsx, src/screens/signin-restore-wallet.tsx, src/screens/signin-store-wallet.tsx, src/screens/signin.tsx, src/screens/signup-store-wallet.tsx, src/screens/signup.tsx
* fix recovery wallet flow
* fix #115 textarea height
* fix #115 page paddings
=> change recovery flow

src/components/bottom-sheet.tsx, src/components/restore-password.tsx, src/contexts/contacts.ts, src/contexts/transactions.ts, src/contexts/wallets.ts
=> fix #104: fix reset wallet popup

src/components/settings-button.tsx, src/components/ui/data-content.tsx, src/components/ui/menu-navigation-button.tsx, src/components/wallet-create.tsx, src/components/wallet-row.tsx, src/screens/settings-account-detail.tsx, src/screens/transaction-detail.tsx
* fix #148 
* fix #149 
* fix #150 
* fix #151
=> markup fixes

src/components/ui/text-field.tsx, src/components/ui/text.tsx, src/screens/home.tsx
=> prevent font scaling

src/components/ui/text.tsx, src/types.ts
fix for #203 
https://stackoverflow.com/a/54960755/3834001
=> Fix font for Text - Android

src/components/ui/button.tsx
=> fix for button

src/screens/home-feed.tsx, src/types.ts
=> Fix for transactions

src/contexts/wallets.ts, src/screens/ledger-store-wallet.tsx, src/screens/signin-store-wallet.tsx, src/screens/signup-store-wallet.tsx, src/types.ts
=> Handle errors

src/screens/settings-about.tsx
=> Hidden rate button

src/contexts/app.ts, src/helpers/create-theme.ts, src/hooks/index.tsx, src/hooks/use-theme.ts, src/models/index.ts, src/models/user.ts, src/screens/settings-language.tsx, src/types.ts
=> dark theme preparement

src/components/ledger-bluetooth/ledger-bluetooth.tsx
[#310](https://github.com/haqq-network/haqq-wallet/issues/310)
=> Fix layout bluetooth

src/components/transaction-address.tsx, src/components/ui/text-field.tsx
[#307](https://github.com/haqq-network/haqq-wallet/issues/307)
=> Fix android input height

src/components/transaction-sum.tsx
=> hide sum and fix text

src/screens/signin-restore-wallet.tsx, src/screens/signin-store-wallet.tsx, src/types.ts
=> fix try again phrase

src/colors.ts, src/components/ui/text.tsx
- `color` property from now accepts Color variables and string
- `i18n` for direct access of I18N variables
=> refactor text component

ios/Podfile.lock, src/components/ui/swipeable-button.tsx
=> Animation changes in swipeable

src/components/ui/input.tsx, src/components/ui/labeled-block.tsx, src/components/ui/text-field.tsx
Fixes #431
- remove line height from input
- remove TouchableWithoutFeedback from TextInput as useless
- refactor colors
=> input line height

src/components/backup-notification/backup-notification.tsx, src/components/ui/button.tsx, src/components/ui/text.tsx
- `i18n` props added to Button
=> Button i18n

src/screens/backup-verify.tsx
=> fix backup error

src/components/pin/pin.tsx, src/components/staking-validators/staking-validators.tsx, src/components/staking-validators/validator-row.tsx, src/components/ui/info-box.tsx, src/components/ui/section-header.tsx, src/components/ui/text.tsx, src/i18n.ts, src/models/staking-metadata.ts, src/screens/staking-validators.tsx, src/types.ts
- validators sorting
- validator row addition information
=> Staking Validator Row sort & addition information

src/components/ui/button.tsx, src/components/ui/icon.tsx, src/components/wallet-create.tsx, src/i18n.ts, src/screens/welcome.tsx
=> fix welcome texts

src/components/ui/popup-container.tsx, src/components/visible-account-selector/visible-account-selector.tsx
Fixes #
- fix error with virtualised error
=> fix virtualized error

android/app/build.gradle, android/build.gradle
- remove google services from android
=> remove google services

src/components/ui/labeled-block.tsx
=> fix input border

src/screens/settings-providers.tsx
=> fix: show back button in providers

docs/code-standard.md
- Add information about basics of architecture our app
- Actualise some outdated points
=> docs: architecture 

src/app.tsx, src/contexts/app.ts
Fixes #479 
- change place for migration run
=> fix: change place for migration run

src/contexts/transactions.ts, src/helpers/capture-exception.ts, src/models/transaction.ts
Fixes #482
- add default value for gas price
- add external information for sentry
=> fix: add default value for gas price

.github/PULL_REQUEST_TEMPLATE.md, README.md, docs/contribution.md
=> docs: add contribution rules

.github/workflows/slack-notify.yml
=> chore: add slack basic

src/screens/transaction-contact-edit.tsx
- Replace navigation hook
the easiest refactoring on the planet
=> refactor(TransactionContactEdit): code

src/contexts/wallets.ts
=> fix(Wallet): show account error

src/components/bottom-popups/popup-bottom-container.tsx, src/components/bottom-sheet.tsx, src/components/modals/error-account-added.tsx, src/components/modals/error-create-account.tsx, src/components/modals/no-internet.tsx, src/i18n.ts, src/screens/settings-test.tsx, src/variables.ts
Fixes #558, #505 
- BottomPopupContainer: change duration
=> refactor(BottomPopupContainer): change duration and fix modals

src/models/index.ts
=> fix(System): up realm version

src/components/ui/menu-navigation-button.tsx
- SettingsHome: fix left icons size
=> fix(Settings): fix left icons size

src/components/settings-address-book.tsx, src/components/settings-provider-edit/settings-provider-edit.tsx, src/components/settings-provider-edit/wrapped-input.tsx, src/components/singin-restore-wallet/signin-restore-wallet.tsx, src/components/transaction-address.tsx, src/components/ui/text-field.tsx, src/components/ui/text.tsx, src/i18n.ts
Fixes #562 
- TextInput: change behaviour
- ProviderForm: fixes
- ProviderForm: errors
- RestoreWallet: remove autoFocus
=> refactor(TextInput): change behaviour

src/components/singin-restore-wallet/signin-restore-wallet.tsx, src/screens/signin-restore-wallet.tsx
Fixes #627 
- RestoreWallet: private key without leading `0x`
=> feature(RestoreWallet): private key

ios/Podfile.lock, ios/haqq.xcodeproj/project.pbxproj, src/components/transaction-sum/transaction-sum.tsx, src/components/ui/sum-block.tsx
=> fix(TransactionSum): fix send to layout and android cursor

src/screens/home.tsx
=> fix(header): header size android and title align center, fix shadow

src/components/singin-restore-wallet/signin-restore-wallet.tsx
=> fix(restoreWallet): paste text color

src/components/bottom-popups/popup-backup-notification/backup-notification.tsx, src/components/bottom-popups/popup-notification/notification-popup.tsx, src/components/bottom-popups/popup-track-activity/popup-track-activity.tsx, src/components/notification-message.tsx, src/components/wallet-card.tsx, src/components/wallet-create.tsx, src/variables.ts
=> fix(toast): fix shadows

src/components/bottom-popups/popup-bottom-container.tsx, src/components/bottom-sheet.tsx
=> fix(popups): bottom sheet and popup fix

src/components/staking-delegate-finish/staking-delegate-finish.tsx, src/components/staking-delegate-preview/staking-delegate-preview.tsx, src/components/staking-undelegate-finish/staking-undelegate-finish.tsx, src/components/ui/icon.tsx, src/components/ui/inline.tsx, src/screens/staking-delegate-finish.tsx, src/screens/staking-undelegate-finish.tsx
=> feat(Staking): add hash button

src/components/address-header.tsx, src/components/address-row.tsx, src/components/qr-scanner-button.tsx, src/components/settings-address-book-edit.tsx, src/components/settings-address-book.tsx, src/components/settings-provider-edit/settings-provider-edit.tsx, src/components/ui/button.tsx, src/variables/common.ts
=> fix(DarkTheme): small fixes

src/components/home-governance/voting-card/voting-card-completed.tsx, src/components/ledger-accounts/ledger-accounts.tsx, src/components/ledger-scan/ledger-scan-row.tsx, src/components/proposal/proposal.tsx, src/helpers/run-until.ts, src/models/provider.ts, src/models/wallet.ts, src/screens/home-staking.tsx, src/screens/staking-delegate-preview.tsx, src/screens/staking-info.tsx, src/services/cosmos.ts, src/services/transport-ledger.ts, src/services/transport.ts, src/types.ts
=> feat(Cosmos): ledger support

src/components/transaction-sum/transaction-sum.tsx
=> fix(TransactionSum): markup

src/components/wallet-card.tsx
Fixes #706 
- hide qr button on wallet card
=> feat(WalletCard): hide qr icon

ios/Podfile.lock, package.json, src/components/bottom-sheet.tsx, src/components/modals/details-qr.tsx, src/components/modals/qr/qr.tsx, src/components/modals/wallets-bottom-sheet.tsx, src/components/restore-password.tsx, src/components/transaction-detail.tsx, src/components/transaction-finish.tsx, src/hooks/use-sum-amount.ts, src/i18n.ts, src/screens/backup-create.tsx, src/screens/backup.tsx, src/screens/signin.tsx, src/screens/transaction-finish.tsx, yarn.lock
Fixes #652
+ on screenshot mnemonic modal
+ refactor
=> fix(Texts): replacing content

src/components/bottom-popups/popup-backup-notification/backup-notification.tsx, src/components/ledger-accounts/ledger-accounts-row.tsx, src/components/restore-password.tsx, src/components/settings-address-book-edit.tsx, src/components/settings-provider-edit/settings-provider-edit.tsx, src/components/ui/button.tsx
Fixes #728 
- fix add button position
=> fix(LedgerAccounts): fix add button position

src/components/settings-provider-edit/settings-provider-edit.tsx, src/components/settings-provider-edit/wrapped-input.tsx
Fixes #
- fix hints for form
- fix spacing for scrollview
=> fix(ProviderEdit): fix hint for form

src/components/staking-validators/validator-row.tsx
Fixes #729 
- fix validator icon
=> fix(Validators): fix validator icon

src/components/settings-security/settings-security.tsx
Fixes #740 
- fix spaces on SettingsSecurity screen
=> fix(SettingsSecurity): fix spaces

src/components/staking-delegate-form/staking-delegate-form.tsx, src/components/staking-undelegate-form/staking-undelegate-form.tsx, src/components/ui/spacer.tsx, src/components/ui/sum-block.tsx
Fixes #
- move block to center
- fix color in sum
=> fix(StakingDelegateForm): move block to center

src/components/home-staking/home-staking.tsx
Fixes #
- fix spaces on buttons
=> fix(HomeStaking): spaces

src/components/staking-info/staking-info.tsx
=> fix(StakingInfo): fix website size

src/components/ui/text-field.tsx
Fixes #731 
- fix text input spacing
=> fix(TextField): space

src/components/restore-agreement/restore-agreement.tsx, src/components/ui/index.ts, src/components/ui/terms.tsx, src/i18n.ts, src/screens/restore.tsx
=> fix(restore agreement): ToS and fix animation margin

src/components/wallet-card.tsx
=> fix(wallet card): icon button size

src/components/create-agreement/create-agreement.tsx
=> fix(create agreement): fix animation

src/components/ui/keyboard-safe-area/index.android.tsx, src/components/ui/keyboard-safe-area/index.ios.tsx, src/hooks/index.ts, src/hooks/use-keyboard-dismiss-in-background.tsx
=> feat(keyboard): dismiss keyboard on background hook

src/components/modals/hide.tsx, src/components/settings-about.tsx, src/i18n.ts
=> refactor: change texts

src/contexts/app.ts
=> fix(Auth): hide window

src/app.tsx, src/components/modals/pin.tsx
=> fix: change theme

src/components/ledger-accounts/ledger-accounts-row.tsx, src/components/ledger-accounts/ledger-accounts.tsx, src/components/ledger-verify/ledger-verify.tsx, src/screens/ledger-accounts.tsx, src/screens/ledger-store-wallet.tsx, src/screens/ledger-verify.tsx, src/types.ts
=> feat(Ledger): multiple accounts

src/components/home-staking/home-staking.tsx, src/components/home-staking/staking-active.tsx, src/components/ledger-accounts/ledger-accounts-row.tsx, src/components/proposal-deposit-finish/proposal-deposit-finish.tsx, src/components/proposal-deposit-preview/proposal-deposit-preview.tsx, src/components/staking-delegate-finish/staking-delegate-finish.tsx, src/components/staking-delegate-preview/staking-delegate-preview.tsx, src/components/staking-info/staking-info.tsx, src/components/staking-undelegate-finish/staking-undelegate-finish.tsx, src/components/staking-undelegate-preview/staking-undelegate-preview.tsx, src/components/staking-validators/validator-row.tsx, src/components/transaction-finish.tsx, src/components/ui/network-fee.tsx, src/components/ui/sum-block.tsx, src/components/wallet-card.tsx, src/models/transaction.ts, src/utils.ts, src/variables/common.ts
- use single number precision variable
- format number to floor of 10**NUM_PRECISION
=> feat(NumberPrecission): use single number precission and format number to floor

src/components/settings-account-detail.tsx, src/contexts/wallets.ts, src/event-actions/on-wallet-create.ts, src/hooks/use-wallet.ts, src/models/index.ts, src/models/wallet.ts, src/screens/backup-verify.tsx, src/screens/settings-account-detail.tsx, src/screens/settings-account-edit.tsx, src/screens/signin-store-wallet.tsx, src/screens/signup-store-wallet.tsx, src/types.ts
=> refactor: use realm wallet

src/screens/signin-restore-wallet.tsx
=> fix: mnemonic to lowercase

src/hooks/use-wallet.ts, src/screens/settings-account-detail.tsx
=> fix: crash on remove wallet

src/components/singin-restore-wallet/signin-restore-wallet.tsx
=> fix: check private key length

ios/Podfile.lock, package.json, src/app.tsx, yarn.lock
- update sentry
- add breadcrumbs
=> chore: update sentry and add breadcrumbs

src/app.tsx, src/components/staking-validators/staking-validators.tsx, src/components/ui/custom-header/search-line.tsx, src/screens/staking-validators.tsx, src/types.ts
=> feat: validators search

src/models/governance-voting.ts, src/screens/home.tsx, src/screens/proposal.tsx, src/services/cosmos.ts
=> refactor: proposal

src/services/cosmos.ts, src/types/cosmos.d.ts
- simulate transaction before sending
=> feat: simulate tx before sending

src/components/modals/transaction-error.tsx, src/i18n.ts, src/screens/modals.tsx, src/screens/staking-delegate-preview.tsx, src/screens/staking-undelegate-preview.tsx
- show error for failed transaction
=> feat: show error for failed transaction

src/components/ui/card.tsx, src/variables/common.ts
=> fix: max card height

src/components/modals/pin.tsx, src/components/ui/sum-block.tsx, src/screens/settings-address-book.tsx, src/screens/transaction-sum.tsx
=> fix: vibrate in app

src/components/transaction-detail.tsx, src/helpers/index.ts, src/helpers/prepare-transactions.ts, src/hooks/use-sum-amount.ts, src/models/transaction.ts, src/screens/home-feed.tsx, src/screens/transaction-detail.tsx, src/utils.ts
- fix transactions
- fix max amount
=> fix: transactions

src/models/user.ts, src/variables/common.ts
=> feat: pin timer

src/models/wallet.ts
Fixes #818 
- change pin issue
=> fix(Wallet): change pin issue

src/screens/settings-account-detail.tsx
- loading during remove account
=> feat(Wallet): loading during remove account

src/contexts/app.ts
Fixes #814 
- try to fix bug with inifinity loading
=> fix(Login): try to fix bug with inifinity loading

src/hooks/use-sum-amount.ts
Fixes #752 
- min transaction sum
=> fix: min transaction sum

src/screens/ledger-accounts.tsx, src/screens/ledger-scan.tsx, src/screens/ledger-verify.tsx
Fixes #548 
- check bluetooth before using
=> feat: check bluetooth before using

ios/Podfile.lock, package.json, src/models/migration-wallets.ts, yarn.lock
=> fix: provider errors

ios/haqq/AppDelegate.mm, src/screens/signin-store-wallet.tsx
=> fix: wallet errors

src/components/staking-delegate-preview/staking-delegate-preview.tsx, src/components/staking-undelegate-preview/staking-undelegate-preview.tsx, src/components/transaction-confirmation/transaction-confirmation.tsx, src/i18n.ts, src/screens/staking-delegate-preview.tsx, src/screens/staking-undelegate-preview.tsx, src/screens/transaction-confirmation.tsx, src/utils.ts
=> feat: human readable errors

src/app.tsx, src/contexts/app.ts, src/event-actions/on-app-started.ts, src/models/user.ts
- try to fix error on onboarding
=> fix: try to fix error on onboarding

src/event-actions/on-push-subscription-add.ts, src/event-actions/on-wallet-create.ts, src/services/push-notifications.ts
=> fix: push notifications

src/components/pin-guard/pin-guard.tsx, src/i18n.ts, src/screens/pin-guard.tsx
=> fix: pin-guard

src/components/ui/card.tsx
=> fix: preview image width

src/components/backup-verify/backup-verify.tsx
Fixes #872 
-  backup check button
=> fix: backup check button

ios/Podfile.lock, src/components/staking-delegate-form/staking-delegate-form.tsx, src/components/staking-delegate-preview/staking-delegate-preview.tsx, src/i18n.ts
=> feat: delegate attention

src/helpers/prepare-transactions.ts
=> fix: error with sorting date

src/screens/pin-guard.tsx
Fixes #883 
- guard screen successful entry
=> fix: guard screen successful entry

ios/haqq/AppDelegate.mm
Fixes #884 
- cleanup storage on install
=> fix: cleanup storage

index.js, src/debug-vars.ts
=> fix(Sentry): loop warning

android/app/build.gradle, ios/haqq/Info.plist, package.json
=> feat: version

android/app/build.gradle, android/build.gradle
=> fix: android build

src/components/ledger-scan/ledger-scan-row.tsx, src/components/ledger-scan/ledger-scan.tsx, src/screens/ledger-scan.tsx
rollback
Fixes #
- fix connect ledger screen
=> fix: ledger connect

android/app/src/main/java/com/haqq/wallet/MainApplication.kt, android/app/src/main/java/com/haqq/wallet/cloud/CloudManager.kt, android/app/src/main/java/com/haqq/wallet/cloud/CloudPackage.kt, ios/haqq.xcodeproj/project.pbxproj, ios/haqq/haqq.entitlements, ios/services/Cloud/Cloud.m, ios/services/Cloud/Cloud.swift, src/components/bottom-popups/popup-backup-mpc-notification/backup-mpc-notification.tsx, src/event-actions/on-wallet-mpc-check.ts, src/helpers/get-google-tokens.ts, src/helpers/get-provider-storage.ts, src/screens/mpc-backup.tsx, src/screens/mpc-store-wallet.tsx, src/screens/popup-backup-mpc-notification.tsx, src/screens/settings-test.tsx, src/services/async-local-storage.ts, src/services/cloud.ts, src/services/google-drive.ts, src/services/provider-mpc.ts
=> feat: use icloud for ios

ios/services/Cloud/Cloud.swift, package.json, src/event-actions/on-wallet-mpc-check.ts, src/event-actions/on-wallet-mpc-saved.ts, src/helpers/get-provider-storage.ts, src/screens/mpc-networks.tsx, src/screens/popup-backup-mpc-suggestion.tsx, src/services/google-drive.ts, src/services/provider-mpc.ts, yarn.lock
=> fix: mpc storage

src/components/hcaptcha.js, src/debug-vars.ts
=> fix: captcha

.env.example, .github/workflows/distribute-android.yml, .github/workflows/distribute-ios.yml, src/env.d.ts, src/services/provider-mpc.ts
=> feat: move to variables

src/components/settings-account-detail/settings-account-detail.tsx
=> fix: accounts social login

package.json, src/components/bottom-popups/popup-backup-mpc-suggestion/backup-mpc-suggestion.tsx, src/components/bottom-popups/popup-bottom-container.tsx, src/components/captcha.tsx, src/components/hcaptcha.js, src/components/signin-not-exists.tsx, src/components/signin-not-recovery.tsx, src/components/wallet-protection.tsx, src/screens/signin-networks.tsx, src/screens/signin-not-exists.tsx, src/types.ts, yarn.lock
Fixes #
- accounts social login
- cleanup code
- update mpc version
=> fix: accounts social login & cleanup code

src/i18n.ts
=> fix(mpc): line break

src/components/wallet-connect-approval.tsx, src/hooks/use-previous.ts, src/hooks/use-wallet-connect-session.ts, src/screens/wallet-connect-sign.tsx
Fixes #
- Close the sign operation screen when the session is disconnected.
=> fix(WalletConnect): reject

src/components/settings-theme/settings-theme.tsx, src/models/user.ts
Fixes #
- change theme settings
=> feat: change theme settings

src/services/cosmos.ts
=> fix: cosmos error

src/env.d.ts, src/event-actions/on-app-started.ts, src/helpers/isFeatureEnabled.ts, src/screens/signin.tsx, src/screens/signup.tsx
=> feat: feature flag for mpc

package.json, src/app.tsx, src/contexts/app.ts, src/event-actions/index.ts, src/event-actions/on-dynamic-link.ts, src/events.ts, src/models/index.ts, src/models/refferal.ts, src/types.ts, yarn.lock
=> feat: store refs into table

src/components/reward-banner.tsx, src/components/wallets.tsx, src/hooks/use-active-refferal.ts, src/hooks/use-refferals.ts, src/i18n.ts, src/screens/wallets.tsx, src/variables/common.ts
Fixes #
-  added reward banner
=> feat(RefferalBanner): added reward banner

src/app.tsx, src/components/account-info/account-info-header.tsx, src/components/account-info/account-info.tsx, src/components/account-info/index.ts, src/components/popup-header.tsx, src/components/popup/dismiss-popup-button.tsx, src/components/popup/go-back-popup-button.tsx, src/components/popup/spacer-popup-button.tsx, src/components/wallet-card.tsx, src/components/wallets.tsx, src/helpers/filter-transactions.ts, src/helpers/get-wallet-title.ts, src/helpers/prepare-transactions.ts, src/helpers/screen-options.ts, src/i18n.ts, src/models/index.ts, src/models/transaction.ts, src/screens/account-info.tsx, src/screens/home-feed.tsx, src/screens/transaction.tsx, src/screens/wallet-connect-application-details-popup.tsx, src/screens/wallet-connect-application-list-popup.tsx, src/screens/wallet-connect.tsx, src/screens/wallet-protection-popup.tsx, src/screens/wallet-selector-screen.tsx, src/screens/wallets.tsx, src/types.ts
https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=5466-85392&t=2ljVmDEuH4n7og70-4
- account info page
=> feat: account info page

src/components/transactions/send.tsx, src/contexts/transactions.ts, src/event-actions/index.ts, src/event-actions/on-transaction-check.ts, src/event-actions/on-transactions-load.ts, src/events.ts, src/models/transaction.ts, src/screens/home-feed.tsx, src/screens/transaction-confirmation.tsx, src/screens/transaction-ledger.tsx
- change transaction check algorhytm
=> fix: transaction check

src/models/user.ts
=> fix: ios theme crash

src/components/browser-error.tsx
Fixes #
- fix browser error page layout
=> fix(Web3Browser): browser error page

src/components/json-rpc-transaction-info.tsx, src/components/web3-browser/web3-browser.tsx, src/debug-vars.ts, src/helpers/webview-logger.ts, src/models/web3-browser-search-history.ts, src/screens/web3-browser.tsx, src/services/json-rpc-middleware/json-rpc-methods-handlers.ts, src/services/sign-json-rpc-request.ts
Fixes #
- smart contracts support for Web3Browser
=> feat(Web3Browser): sign contract

src/event-actions/index.ts, src/event-actions/on-push-notification.ts, src/events.ts, src/screens/settings-test.tsx, src/services/push-notifications.ts, src/types.ts
=> feat: send message by topic

src/debug-vars.ts, src/env.d.ts, src/event-actions/on-transaction-create.ts, src/event-actions/on-transactions-load.ts, src/models/index.ts, src/models/transaction.ts, src/screens/transaction-confirmation.tsx
=> fix: transaction create

src/components/banners/banners.tsx, src/components/home-banner.tsx, src/components/wallets.tsx, src/event-actions/on-banner-notification-create.ts, src/event-actions/on-banner-notification-topic-create.ts, src/event-actions/on-banner-notifications-snooze.ts, src/event-actions/on-banner-notifications-topic-snooze.ts, src/event-actions/on-banner-notifications-topic-subscribe.ts, src/models/banner.ts, src/models/index.ts, src/screens/wallets.tsx
- banners refactor
https://www.figma.com/file/KoyH6PqWqfOwyIVDjnLlOk/%F0%9F%93%B1-Wallet?node-id=6549-142600&t=g4Afi95yA86G32Y6-4
=> feat: banners refactor

src/components/news-detail/news-detail.tsx
=> fix: news markdown

src/components/browser-edit-bookmarks.tsx, src/components/browser-search-page.tsx, src/components/web3-browser/web3-browser.tsx, src/screens/browser-home-page-screen.tsx, src/screens/settings-test.tsx, src/screens/web3-browser.tsx
Fixes #
- web3 browser strict url
=> feat: web3 browser strict url

src/services/wallet-connect.ts
Fixes #
- wallet connect approve request
=> fix: wallet connect approve request

src/screens/home.tsx
=> feat(Web3Browser): enable browser

src/components/browser-edit-bookmarks.tsx, src/components/browser-home-page.tsx, src/screens/web3-browser.tsx
Fixes #
- hide web3 browser ui elements
=> fix: web3 browser ui

index.js, ios/Podfile.lock, ios/haqq.xcodeproj/project.pbxproj, package.json, src/event-actions/on-wallet-connect-uri.ts, src/i18n.ts, src/screens/ledger-bluetooth.tsx, src/screens/onboarding-finish.tsx, src/services/wallet-connect.ts, yarn.lock
Fixes #
- fix WalletConnect pairing
=> fix(WalletConnect): pairing

index.js, src/components/browser-home-page.tsx, src/components/modals/qr/qr.tsx
=> fix: web3 ui bugs

android/app/src/main/java/com/haqq/wallet/cloud/CloudManager.kt, src/app.tsx, src/contexts/app.ts, src/helpers/await-navigator-is-ready.ts, src/helpers/get-provider-for-new-wallet.ts, src/screens/signup-network-exists.tsx, src/screens/signup-store-wallet.tsx
=> refactor: cleanup

src/components/news-detail/news-detail.tsx, src/components/news/news-row.tsx
=> fix: news date

src/components/modals/qr/qr.tsx, src/event-actions/on-wallet-connect-uri.ts, src/i18n.ts, src/services/wallet-connect.ts
=> fix:(WalletConnect): pair

src/screens/transaction-ledger.tsx
Fixes #
- Ledger send transaction
=> fix(Ledger): send transaction

src/components/singin-restore-wallet/signin-restore-wallet.tsx
Fixes #
- fixed paste from clipboard button
=> fix: paste from clipboard button

src/event-actions/on-wallet-connect-sign-transaction.ts, src/helpers/is-feature-enabled.ts
Fixes #
- lock wallet connect sign
=> feat: lock wallet connect sign

src/variables/common.ts
=> refactor: pin timeout

src/event-actions/on-news-sync.ts, src/event-actions/on-push-notification.ts, src/event-actions/on-transactions-load.ts, src/services/airdrop.ts, src/services/backend.ts, src/services/cosmos.ts, src/services/google-drive.ts, src/services/provider-mpc.ts, src/services/push-notifications.ts, src/utils.ts
=> fix: http response

src/components/captcha.tsx, src/components/hcaptcha/hcaptcha.tsx, src/components/home-earn.tsx, src/components/raffle-details.tsx, src/components/raffle-reward.tsx, src/components/slider-captcha/slider-captcha.tsx, src/components/ui/loading.tsx, src/helpers/is-feature-enabled.ts, src/screens/home-earn.tsx, src/screens/raffle-details.tsx, src/services/backend.ts, src/types.ts
Fixes #
- raffles add missing logic
=> feat: raffles add missing logic

src/components/raffle-details.tsx, src/i18n.ts, src/screens/staking-info.tsx, yarn.lock
Fixes #
- fix validator info delegate/undelegate
=> fix: validator info

src/event-actions/on-banner-notifications-topic-subscribe.ts, src/event-actions/on-banner-notifications-topic-unsubscribe.ts, src/event-actions/on-banner-notifications-turn-on.ts, src/event-actions/on-track-event.ts, src/screens/backup-finish.tsx, src/screens/create.tsx, src/screens/onboarding-finish.tsx, src/screens/restore.tsx, src/screens/signin.tsx, src/screens/signup.tsx, src/screens/transaction-confirmation.tsx, src/screens/transaction-ledger.tsx, src/services/airdrop.ts, src/types.ts
=> feat: adjust events

src/contexts/app.ts
Fixes #
- wallet providers reset
=> fix: wallet providers reset

src/screens/popup-notification.tsx
Fixes #
- push notifications popup
=> fix: notification popup

src/components/bottom-sheet.tsx
=> fix: bottom sheet

src/components/home-earn.tsx, src/components/slider-captcha/slider-captcha.tsx, src/components/ui/raffle-block-list.tsx, src/components/ui/raffle-block.tsx, src/event-actions/on-dynamic-link.ts, src/screens/home-earn.tsx
- fix: raffles
- fix: slider captcha
=> fix: raffles

src/event-actions/on-banner-claim-airdrop.ts, src/services/airdrop.ts
=> feat: claim and signature

src/app.tsx, src/services/backend.ts, src/services/remote-config/index.ts, src/services/remote-config/remote-config-service.ts, src/services/remote-config/remote-config-types.ts, src/services/wallet-connect.ts, src/utils.ts
=> feat: remote config

src/components/news-detail/news-detail.tsx, src/screens/browser-home-page-screen.tsx, src/screens/home-earn.tsx, src/screens/home-governance.tsx, src/screens/home-settings.tsx, src/screens/home-staking.tsx, src/screens/news-list.tsx, src/screens/settings-account-detail.tsx, src/screens/staking-delegate-preview.tsx, src/screens/staking-validators.tsx, src/types.ts
=> feat: events

src/event-actions/on-app-logged-in.ts
Fixes #
-  login without internet
=> fix: login without internet

src/screens/modals-screen.tsx
=> fix: modals types

src/components/json-rpc-sign.tsx, src/event-actions/on-wallet-connect-sign-transaction.ts, src/helpers/is-feature-enabled.ts, src/hooks/use-remote-config.ts, src/screens/json-rpc-sign-screen.tsx, src/services/backend.ts, src/services/remote-config/remote-config-service.ts, src/services/remote-config/remote-config-types.ts
=> feat: web3 app whitelist

src/components/home-staking/home-staking.tsx, src/screens/home-earn.tsx
=> feat: earn reward

src/components/slider-captcha/slider-captcha.tsx, src/utils.ts
=> fix: puzzle captcha

android/link-assets-manifest.json, ios/haqq.xcodeproj/project.pbxproj, ios/link-assets-manifest.json
=> fix: link assets

src/components/account-info/account-info.tsx, src/components/home-feed.tsx, src/components/wallets.tsx, src/helpers/is-feature-enabled.ts
=> feat: nft feature enabled

src/components/captcha.tsx, src/components/home-earn.tsx, src/components/modals/capthca-modal.tsx, src/components/slider-captcha/slider-captcha.tsx, src/components/ui/rive-wrapper.tsx, src/contexts/app.ts, src/helpers/capture-exception.ts, src/helpers/get-leading-account.ts, src/screens/home-earn.tsx
Fixes #
- slider captcha error while shown puzzle
- earn shown rewards
- captcha modal close
-  getting leading account
- disable biometry while pin banned
-  raffles refresh contoller
=> fix: release hotfix

src/app.tsx, src/components/bottom-sheet.tsx, src/components/captcha.tsx, src/components/modal.tsx, src/components/modals/modal-wrapper.tsx, src/components/modals/no-internet.tsx, src/components/slider-captcha/slider-captcha.tsx, src/components/ui/spacer.tsx, src/screens/modals-screen.tsx, src/screens/settings-test.tsx, src/types.ts
=> refactor: modals

src/components/transaction-address.tsx, src/components/ui/text-field.tsx, src/screens/onboarding-finish.tsx
Fixes #
- [ignoring proceed button](https://github.com/haqq-network/haqq-wallet/commit/52512cdcfd0bc888563c21bb251c52c3a9421c59)
- [limit multilines input](https://github.com/haqq-network/haqq-wallet/commit/f6dfd4c152c2bc9bae34aad2764e875a1e492482)
=> fix: bugfix

src/components/account-info/account-info.tsx, src/components/banners/banners.tsx, src/components/home-feed.tsx, src/components/top-tab-navigator-large.tsx, src/components/ui/spacer.tsx, src/components/wallets/wallets.tsx, src/i18n.ts, src/screens/web3-browser-popup.tsx
=> fix: home spacers

src/components/home-earn.tsx, src/components/raffle-details.tsx, src/components/ui/raffle-block.tsx, src/helpers/get-leading-account.ts, src/i18n.ts, src/screens/home-earn.tsx, src/screens/raffle-details.tsx
=> feat: raffles loader

src/components/banners/banners.tsx, src/contexts/app.ts, src/event-actions/index.ts, src/event-actions/on-address-book-create.ts, src/event-actions/on-app-started.ts, src/event-actions/on-staking-sync.ts, src/event-actions/on-wallet-create.ts, src/event-actions/on-wallets-balance-check.ts, src/events.ts, src/screens/home-feed.tsx, src/screens/settings-providers.tsx, src/utils.ts
=> fix: prerelease fixes

src/jailbreak.tsx
Fixes #
-  jailbreak hide splash screen
=> feat: jailbreak hide splash screen

src/components/modals/qr/qr.tsx
Fixes #
-  vibration wrapper for qr modal
=> fix: vibration wrapper for qr modal

android/app/src/main/java/com/haqq/wallet/version/VersionManager.kt, ios/extensions/UIDevice+modelName.swift, ios/haqq.xcodeproj/project.pbxproj, ios/services/Version/Version.swift, src/screens/settings-test.tsx, src/services/version.ts
=> feat: user-agent

src/components/web3-browser/web3-browser-helper.ts
Fixes #
-  web3 browser handle wallet connect
=> feat: web3 browser handle wallet connect

src/event-actions/on-staking-sync.ts, src/services/cosmos.ts
- https://haqq-network.sentry.io/issues/4270653555/?project=4504355463626752
- https://haqq-network.sentry.io/issues/4274060425/?project=4504355463626752
- https://haqq-network.sentry.io/issues/4273482644/?project=4504355463626752
=> fix: postrelease bugs

ios/AppDelegate.swift, src/jailbreak.tsx, src/types.ts
=> feat: jailed event

src/services/wallet-connect.ts
=> fix: wallet connect

src/components/home-news.tsx, src/components/news/news-row-list.tsx, src/models/rss-news.ts, src/screens/home-news.tsx, src/screens/settings-test.tsx
=> fix: rss news pagination

src/services/wallet-connect.ts
Fixes #
- wallet connect redirect
=> fix: wallet connect redirect

ios/AppDelegate.swift, ios/haqq.xcodeproj/project.pbxproj, ios/haqq/Info.plist
=> fix: disable audio mode

.github/workflows/distribute-android.yml, .github/workflows/distribute-ios.yml, package.json, src/env.d.ts, src/event-actions/on-app-started.ts, src/event-actions/on-banner-gasdrop-create.ts, src/services/airdrop.ts, yarn.lock
=> feat: gasdrop

src/contexts/app.ts
Fixes #
- iOS change theme listener
=> fix: change theme listener

package.json, src/contexts/app.ts, src/screens/settings-security-pin.tsx, yarn.lock
=> feat: password

src/components/in-app-browser.tsx, src/components/web3-browser/web3-browser-helper.ts, src/helpers/web3-browser-utils.ts, src/services/wallet-connect.ts
Fixes #
- browser haqq deeplink support
=> feat: browser haqq deeplink support

src/event-actions/on-banner-claim-airdrop.ts, src/i18n.ts, src/services/airdrop.ts
=> fix: airdrop

src/components/news/news-card-carousel.tsx, src/components/news/news-card.tsx, src/screens/news-detail.tsx
Fixes #
- optimizing news render
=> refactor: optimizing news render

src/components/modals/qr/qr.tsx, src/hooks/use-android-back-handler.tsx, src/screens/transaction-account.tsx, src/screens/transaction-address.tsx, src/screens/transaction-confirmation.tsx, src/screens/transaction-contact-edit.tsx, src/screens/transaction-finish.tsx, src/screens/transaction-ledger.tsx, src/screens/transaction-nft-confirmation.tsx, src/screens/transaction-nft-finish.tsx, src/screens/transaction-sum-address.tsx, src/screens/transaction-sum.tsx
Fixes #
-  android back handler
=> feat: android back handler

src/components/account-info/account-info.tsx, src/components/nft-viewer/mock.ts, src/screens/home-feed.tsx
=> fix: issue #1157

index.js
=> fix: issue #1158

src/components/browser-search-page.tsx, src/components/web3-browser/web3-browser.tsx, src/screens/transaction-address.tsx, src/screens/transaction-sum-address.tsx
=> fix: issue #1161

android/app/src/main/java/com/haqq/wallet/haptic/HapticManager.kt
=> fix: issue #1163

src/contexts/app.ts, src/events.ts
Fixes #
- infinity biometry auth
=> fix: infinity biometry auth

patches/react-native-touch-id+4.4.1.patch
=> fix: issue #1166

src/components/ui/rive-wrapper.tsx
=> fix: typo in rive-wrapper.tsx

src/contexts/app.ts
=> fix: biometry auth

src/components/news/news-card.tsx, src/components/news/news-row.tsx, src/components/onboarding-track-user-activity/onboarding-track-user-activity.tsx, src/components/ui/icon.tsx
Fixes #
- news spacing
- track user activity spacing
- news placeholder
=> fix: spacing & placeholder

src/components/raffle-details.tsx, src/components/ui/circular-progress.tsx, src/components/ui/raffle-block.tsx, src/components/ui/timer.tsx, src/hooks/use-color.ts, src/hooks/use-timer.ts, src/screens/home-earn.tsx, src/types.ts, src/utils.ts
Fixes #
-  Closes: [HQM-18](https://linear.app/haqq/issue/HQM-18/clean-up-earn-section-eliminate-negative-dates-and-pull-timer-from)
=> refactor: HQM-18

src/components/home-governance/voting-card/voting-card-active.tsx, src/components/proposal/voting-card-detail.tsx, src/helpers/governance.ts, src/models/governance-voting.ts, src/utils.ts
=> fix: HQM-19

package.json, scripts/clean-ios-app.sh
Fixes #
- ios clean script
https://github.com/haqq-network/haqq-wallet/assets/25716589/e4c4ed83-4b6f-45af-8851-c03568882318
=> feat: ios clean script

src/event-actions/on-wallet-connect-sign-transaction.ts, src/screens/json-rpc-sign-screen.tsx, src/screens/wallet-connect-approval.tsx, src/services/json-rpc-middleware/index.ts, src/services/wallet-connect.ts, src/utils.ts
=> refactor: error handlers

src/contexts/app.ts, src/helpers/async-event-emitter.ts
=> feat: async event emitter

src/utils.ts
=> fix: HQW-40

src/components/news/news-card.tsx
Fixes #
- news card android issue
=> fix: news card android issue

src/services/eth-network.ts
=> fix: get balance fallback

src/event-actions/index.ts, src/event-actions/on-provider-changed.ts
fix: #HQM-33
- on provider changed event
=> feat: on provider changed event

src/debug-vars.ts, src/event-actions/index.ts, src/helpers/async-event-emitter.ts
Fixes #
-  added logs to async event emitter
-  revoke callbackWrapper
=> refactor: async event emitter

src/models/index.ts
Fixes #
- realm variable bool migration
=> fix: realm variable bool migration

src/event-actions/on-app-started.ts, src/event-actions/on-provider-changed.ts, src/event-actions/on-vesting-sync.ts, src/event-actions/on-wallet-create.ts, src/models/index.ts, src/models/vesting-metadata.ts, src/services/cosmos.ts, src/types/cosmos.d.ts
Fixes #HQM-50
- vesting fetching
=> feat: vesting

package.json, src/components/slider-captcha/slider-captcha.tsx
Fixes #
- slider captcha layout
=> fix: slider captcha layout

src/event-actions/on-need-update.ts, src/helpers/check-app-version.ts
=> fix: app update

.github/workflows/distribute-android.yml, .github/workflows/distribute-ios.yml, src/contexts/app.ts, src/env.d.ts, src/screens/settings-test.tsx, src/services/backend.ts
=> feat: select backend

ios/haqq/haqq.entitlements, src/event-actions/on-app-started.ts
=> test: dynamic link

src/components/modals/raffle-agreement.tsx, src/event-actions/on-earn-get-ticket.ts
=> fix: raffle agreement

src/screens/ledger-bluetooth.tsx
Fixes #
-  system dialog request bluetooth
=> fix: system dialog request bluetooth

src/components/modals/qr/qr.tsx, src/event-actions/on-deep-link.ts, src/types.ts
=> fix: handle QR data

src/components/modals/raffle-agreement.tsx, src/components/raffle-details.tsx, src/i18n.ts, src/services/cosmos.ts, src/variables/common.ts
Fixes #
- raffle agreement platform-dependent text
=> refactor: raffle agreement platform-dependent text

src/helpers/check-app-version.ts
Fixes #
-  check app version regexp
=> fix: check app version regexp

src/services/balance.ts
=> fix: balance constuctor

ios/haqq.xcodeproj/project.pbxproj, src/event-actions/on-remote-config-sync.ts, src/event-actions/on-staking-sync.ts, src/event-actions/on-vesting-sync.ts, src/event-actions/on-wallet-create.ts, src/event-actions/on-wallets-balance-check.ts, src/models/index.ts, src/models/provider.ts, src/models/wallet.ts, src/services/cosmos.ts, src/services/indexer.ts, src/services/remote-config/remote-config-service.ts, src/services/remote-config/remote-config-types.ts
Fixes #HQM-69
- fetch balances from backend
=> feat: balance backend

src/components/ui/bar-chart/bar-chart-item.tsx, src/components/ui/bar-chart/bar-chart-text.tsx, src/components/ui/bar-chart/bar-chart.tsx, src/components/ui/bar-chart/index.ts
=> feat: bar chart

src/event-actions/on-banner-claim-airdrop.ts, src/event-actions/on-earn-get-ticket.ts, src/event-actions/on-staking-rewards.ts, src/helpers/await-for-ledger.ts, src/screens/settings-test.tsx, src/screens/transaction-confirmation.tsx, src/services/sign-json-rpc-request.ts
Fixes #
- Closes: HQM-78 HQM-63
=> feat: ledger modal HQM-78 HQM-63

src/app.tsx, src/components/ui/widget-header.tsx
Fixes #
- WidgetHeader description text issue on Android
- Infinity loading splash screen with current backend 
-
-
-
=> fix: current release

src/helpers/screen-options.ts
Fixes #
- fix HeaderBackVisible prop
-
-
=> fix: HQM-62 headerBackVisible prop

src/components/home-settings/home-settings.tsx, src/contexts/app.ts, src/events.ts, src/hooks/use-theme.ts, src/screens/home-settings.tsx
Fixes #
- onThemeChanged event
-
-
=> fix: HQM-70 Theme toggle

src/i18n.ts
Fixes #
- Send to => Sent to
-
-
=> fix: HQM-73 typo in Transaction Details

babel.config.js, package.json, yarn.lock
Fixes #
- add babel-plugin-react-remove-properties
-
-
=> fix: HQM-52 add babel-plugin-react-remove-properties

src/widgets/ad-widget/index.tsx, src/widgets/banner-widget/index.tsx
=> fix: hqm-82

src/event-actions/on-wallet-remove.ts
Fixes #
- remove last wallet bug
=> fix: remove last wallet bug

src/components/raffle-details.tsx, src/helpers/prepare-raffles.ts, src/screens/home-earn.tsx, src/widgets/raffles.widget/index.tsx
=> fix: HQM-65

src/components/in-app-browser.tsx, src/components/web3-browser/web3-browser.tsx, src/screens/in-app-browser.tsx, src/screens/web3-browser.tsx
Fixes #
- handle download files in browser
=> feat: handle download files

src/colors.ts, src/components/ui/shadow-card.tsx, src/variables/common.ts, src/widgets/ad-widget/index.tsx, src/widgets/banner-widget/index.tsx, src/widgets/index.tsx, src/widgets/staking-widget/staking-widget.tsx, src/widgets/transactions-short-widget/transactions-short-widget.tsx
=> fix: HQM-83

src/services/logger.ts
=> add: scope support

src/event-actions/on-app-logged-in.ts, src/event-actions/on-app-reset.ts, src/event-actions/on-wallet-remove.ts, src/models/wallet.ts, src/services/wallet-connect.ts
=> fix: HQM-86

src/event-actions/on-app-reset.ts, src/models/user.ts
=> fix: HQM-92 (lockout policy)

src/components/security-view.tsx, src/components/ui/mnemonic-table/mnemonic-table.tsx
Fixes #
- HQM-91
-
-
Demo:
https://github.com/haqq-network/haqq-wallet/assets/83400198/a58c45b7-6d7b-4932-b020-b614dc657817
https://github.com/haqq-network/haqq-wallet/assets/83400198/7ec4a298-29db-4a66-8bce-f211bb565d92
=> fix: HQM-91

android/sentry.properties, ios/haqq.xcodeproj/project.pbxproj, ios/sentry.properties, package.json, yarn.lock
=> fix: HQM-96

src/screens/home.tsx, src/widgets/transactions-short-widget/index.tsx
=> fix: HQM-97

src/components/web3-browser/web3-browser-action-menu.tsx, src/components/web3-browser/web3-browser-header.tsx, src/components/web3-browser/web3-browser.tsx, src/i18n.ts
=> fix: web3 browser popup

src/app.tsx
Fixes #
- Fixed zero balance at startup
-
-
=> fix: zero balance

.github/workflows/distribute-android.yml, .github/workflows/distribute-ios.yml, src/components/captcha.tsx, src/components/turnstile/index.ts, src/components/turnstile/turnstile-utils.ts, src/components/turnstile/turnstile.tsx, src/screens/settings-test.tsx, src/types/env.d.ts
Fixes #
- cloudflare turnslite captcha
=> feat: cloudflare turnstile captcha

src/event-actions/on-app-logged-in.ts, src/event-actions/on-transactions-load.ts
=> fix: HQM-102 (infinity loader)

src/components/home-feed.tsx, src/widgets/index.tsx, src/widgets/transactions-short-widget/index.tsx, src/widgets/transactions-widget/index.tsx, src/widgets/transactions-widget/transaction-row-widget.tsx, src/widgets/transactions-widget/transactions-widget.tsx
=> fix: HQM-104

src/event-actions/on-banner-gasdrop-create.ts, src/services/airdrop.ts
=> feat: adid

src/event-actions/on-transaction-create.ts, src/models/transaction.ts
Fixes #HQM-105
- transaction wont create if fee is Balance
=> fix: HQM-105 fee as Balance

src/event-actions/on-wallets-balance-check.ts
=> feat: balance fallback

.github/workflows/distribute-android.yml, .github/workflows/distribute-ios.yml, .github/workflows/distribute.yml, src/components/wallet-card.tsx, src/helpers/is-feature-enabled.ts, src/types/env.d.ts
- enable staked vested tokens on variable
=> feat: enable staked vested tokens on variable

src/components/modals/splash.tsx, src/components/ui/text.tsx
=> feat: splash description fade in animation

src/event-actions/on-staking-rewards.ts, src/screens/staking-delegate-finish.tsx, src/variables/common.ts, src/widgets/staking-widget/staking-widget.tsx
Fixes #HQM-111
- fix show reward button
- fix delay for refresh staked
-
=> fix: HQM-111

src/components/transaction-detail.tsx, src/event-actions/on-transactions-load.ts, src/models/index.ts, src/models/transaction.ts
=> fix: HQM-115 HQM-116

src/widgets/index.tsx
=> fix: remove TransactionsShort widget

package.json, src/event-actions/on-staking-rewards.ts, src/helpers/await-for-ledger.ts, yarn.lock
Fixes #
-  get reward from staking
- wait for https://github.com/haqq-network/haqq-wallet-provider-ledger-react-native/pull/6
=> fix(Ledger): get reward from staking

src/event-actions/on-banner-claim-airdrop.ts, src/event-actions/on-banner-gasdrop-create.ts, src/helpers/get_adjust_adid.ts, src/services/airdrop.ts
=> feat: claim uid & adid

src/components/modals/qr/qr.tsx
=> fix: wc connection error

src/services/backend.ts, src/services/push-notifications.ts, src/services/remote-config/remote-config-service.ts
- get post config with addition data
=> feat: post config

src/screens/home.tsx
=> feat: persist browser

ios/haqq.xcodeproj/project.pbxproj, src/components/choose-account/choose-account-footer.tsx, src/components/choose-account/choose-account-row.tsx, src/components/choose-account/choose-account.tsx, src/components/top-tab-navigator.tsx, src/helpers/get-wallets-from-provider.tsx, src/i18n.ts, src/models/index.ts, src/screens/choose-account-screen.tsx, src/screens/signin-restore-wallet.tsx, src/screens/signin-store-wallet.tsx, src/screens/signin.tsx, src/screens/signup-store-wallet.tsx, src/services/indexer.ts, src/types.ts, src/utils.ts, src/variables/common.ts
Fixes #
- HQM-126
- fix for #1275 
-
=> feat: HQM-126 choose mnemonic type flow

src/components/news-detail/news-detail.tsx
Fixes #
- Closed:  HQM-129
- [x ] I have read the rules of [**contribution**](https://github.com/haqq-network/haqq-wallet/blob/main/docs/contribution.md#important-steps).
=> fix: our news preview image

src/services/indexer.ts
=> feat: getContractNames empty call method fix

src/event-actions/on-wallets-balance-check.ts, src/widgets/index.tsx
Fixes #
- blink widgets and empty layout
=> fix: blink widgets and empty layout

src/helpers/verify-cloud.ts, src/screens/signin-store-wallet.tsx
=> fix: sss flow

.github/workflows/distribute-android.yml, .github/workflows/distribute-ios.yml, .github/workflows/distribute.yml, src/app.tsx, src/contexts/app.ts, src/event-actions/on-wallet-remove.ts, src/helpers/get-welcome-screen.tsx, src/helpers/is-feature-enabled.ts, src/services/remote-config/remote-config-types.ts, src/types/env.d.ts
- Get the welcome screen from the config file
=> feat: get welcome screen from config file

src/services/backend.ts, src/widgets/index.tsx
- send chainId for fetch markup
=> feat: send chainId for fetch markup

src/screens/choose-account-screen.tsx, src/screens/signin-store-wallet.tsx
=> feat: add logs for sss

src/services/backend.ts, src/widgets/index.tsx
- Send platform and version in markup
=> feat: platform and version in markup

src/components/animated-balance.tsx, src/components/wallet-card.tsx
=> fix: balance animation

src/widgets/transactions-widget/transaction-row-widget.tsx
=> fix: transaction row height

src/components/onboarding-repeat-pin.tsx, src/components/onboardinng-setup-pin/onboarding-setup-pin.tsx, src/screens/onboarding-repeat-pin.tsx, src/screens/onboarding-setup-pin.tsx, src/types.ts
=> feat: add new retry flow for pin code

src/components/animated-balance.tsx, src/components/wallet-card.tsx, src/event-actions/on-wallet-create.ts, src/event-actions/on-wallets-balance-check.ts, src/helpers/create-wallets-for-provider.ts, src/screens/account-info.tsx, src/screens/ledger-accounts.tsx, src/screens/proposal-deposit-form.tsx, src/screens/sss-store-wallet.tsx, src/screens/staking-delegate-form.tsx, src/screens/total-value-info.tsx, src/screens/transaction-sum.tsx, src/widgets/transactions-widget/index.tsx
Fixes #
- HQM-131
- fix: balance lower than 0.1 is not visible
-
=> feat: implement SSOT for Balance

src/components/news-detail/news-detail.tsx
Fixes #
- fix news image preview
=> fix: news image preview

ios/services/Cloud/Cloud.swift, package.json, src/components/modals/pin.tsx, src/helpers/decrypt-local-share.ts, src/helpers/get-provider-for-new-wallet.ts, src/helpers/verify-cloud.ts, src/i18n.ts, src/screens/signin-networks.tsx, src/screens/signin-pin.tsx, src/screens/signin-store-wallet.tsx, src/screens/signup-networks.tsx, src/screens/signup-pin.tsx, src/screens/signup-store-wallet.tsx, src/screens/sss-migrate-store.tsx, src/screens/sss-store-wallet.tsx, src/types.ts, yarn.lock
Fixes #
- HQM-136
- localShare flow
-
=> feat: HQM-136 localShare flow + retry policy

.env.example, .github/workflows/distribute-android.yml, .github/workflows/distribute-ios.yml, src/helpers/get-app-info.ts, src/helpers/get_adjust_adid.ts, src/services/airdrop.ts, src/services/backend.ts, src/services/provider-sss.ts, src/services/remote-config/remote-config-service.ts, src/services/remote-config/remote-config-types.ts, src/types/env.d.ts, src/widgets/index.tsx
- Move sss verifiers into the config
=> feat: move sss verifiers into config

.env.example, .github/workflows/distribute-android.yml, .github/workflows/distribute-ios.yml, src/components/animated-balance.tsx, src/components/locked-tokens.tsx, src/components/stacked-vested-tokens.tsx, src/components/ui/card-small.tsx, src/event-actions/on-app-review-request.ts, src/event-actions/on-banner-gasdrop-create.ts, src/helpers/async-event-emitter.ts, src/helpers/get-provider-for-new-wallet.ts, src/hooks/use-transaction-list.ts, src/models/provider.ts, src/screens/signin-networks.tsx, src/screens/signin-store-wallet.tsx, src/screens/signup-networks.tsx, src/screens/signup-pin.tsx, src/screens/sss-migrate-networks.tsx, src/screens/sss-migrate-store.tsx, src/screens/sss-store-wallet.tsx, src/services/airdrop.ts, src/services/balance.ts, src/services/logger.ts, src/services/provider-sss.ts, src/services/remote-config/remote-config-service.ts, src/services/remote-config/remote-config-types.ts, src/services/wallet-connect.ts, src/types/env.d.ts, src/utils.ts
=> feat: config variables

docs/inpage-bridge-web3.md, src/components/web3-browser/scripts/inpage-bridge-web3.ts
Fixes #
-  Instructions to Obtain InpageBridgeWeb3.js from MetaMask's mobile-provider
=> feat: inpage bridge web3 readme

src/components/security-view.tsx, src/screens/settings-view-recovery-phrase.tsx
=> fix: security view

src/i18n.ts
=> fix: typos

src/helpers/get-provider-for-new-wallet.ts
=> fix: sss provider initialization

src/app.tsx, src/helpers/get-provider-for-new-wallet.ts, src/models/banner.ts, src/screens/popup-backup-sss-suggestion.tsx, src/screens/signup-store-wallet.tsx
=> fix: slack bugs

src/screens/settings-test.tsx
=> feat: show adid in test page

src/contexts/app.ts, src/models/user.ts, src/screens/signin-pin.tsx
=> feat: add recovery timer

index.js, src/models/banner.ts, src/models/contact.ts, src/services/mmkv.ts, src/types.ts, src/variables/common.ts
=> fix: HQM-152

src/components/in-app-browser.tsx, src/components/web3-browser/web3-browser.tsx
Fixes #
-  update in app browser
=> feat: update in app browser

package.json, src/event-actions/on-wallets-balance-check.ts
=> fix: get balance

src/components/settings-notification.tsx, src/event-actions/on-banner-notifications-topic-subscribe.ts, src/event-actions/on-banner-notifications-topic-unsubscribe.ts, src/event-actions/on-banner-notifications-turn-on.ts, src/event-actions/on-earn-get-ticket.ts, src/event-actions/on-notifications-topic-subscribe.ts, src/event-actions/on-notifications-topic-unsubscribe.ts, src/helpers/get-app-info.ts, src/i18n.ts, src/models/raffles.ts, src/screens/popup-notification-news.tsx, src/screens/settings-notification-screen.tsx, src/services/push-notifications.ts, src/types.ts, src/variables/common.ts
Fixes #
-  raffles notifications
=> feat: raffles notifications

src/components/in-app-browser.tsx, src/components/web3-browser/web3-browser-helper.ts
Fixes #
- browser handle deeplink
=> fix: browser handle deeplink

src/services/cosmos.ts
=> fix: cosmos fee

.github/workflows/distribute-android.yml, .github/workflows/distribute-ios.yml, src/services/mmkv.ts, src/types/env.d.ts
=> feat: env MMKV_KEY

src/event-actions/on-app-review-request.ts, src/event-actions/on-push-notification.ts, src/event-actions/on-staking-sync.ts, src/event-actions/on-sync-app-balances.ts, src/event-actions/on-wallet-connect-sign-transaction.ts, src/event-actions/on-wallets-balance-check.ts, src/event-actions/on-wallets-staking-balance-check.ts, src/event-actions/on-wallets-vesting-balance-check.ts, src/events.ts
Fixes #
- [HQM-26](https://linear.app/haqq/issue/HQM-26/app-events)
-
-
=> refactor: Remove events as strings

src/components/ui/raffle-block.tsx
Fixes #
-  get ticket button smoll width issue
=> fix(Raffles): get ticket button smoll width issue

src/screens/browser-home-page-screen.tsx
Fixes #
- realm reset wallet error
`ERROR  Error: Exception in HostFunction: Accessing object of type Web3BrowserBookmark which has been invalidated or deleted`
=> fix: realm reset wallet error

src/screens/ledger-accounts.tsx
Fixes #
-  empty balance while import ledger account
=> fix: empty balance while import ledger account

src/event-actions/on-transactions-load.ts, src/helpers/explorer-instance.ts, src/services/explorer.ts, src/types.ts
=> feat: explorer api

src/components/account-info/account-info-header.tsx, src/components/account-info/account-info.tsx, src/components/stacked-vested-tokens.tsx, src/components/total-value-info/total-value-info-header.tsx, src/components/total-value-info/total-value-info.tsx, src/components/wallet-card.tsx, src/contexts/app.ts, src/event-actions/on-staking-sync.ts, src/event-actions/on-vesting-sync.ts, src/event-actions/on-wallet-create.ts, src/event-actions/on-wallets-balance-check.ts, src/event-actions/on-wallets-staking-balance-check.ts, src/event-actions/on-wallets-vesting-balance-check.ts, src/hooks/use-wallets-vesting-balance.ts, src/i18n.ts, src/screens/account-info.tsx, src/screens/locked-tokens.tsx, src/screens/total-value-info.tsx, src/services/indexer.ts, src/types.ts, src/variables/common.ts
=> feat: vested tokens

src/screens/signup-pin.tsx
Fixes #
- Sync singup pin component with singin pin
-
-
=> fix: signup pin

ios/Podfile.lock, src/event-actions/on-wallets-balance-check.ts, src/services/eth-network.ts
Fixes #
- HQM-174
- Fix Podfile.lock after RN upgrade
-
=> feat: HQM-174 Balance Caching

src/components/banners/banners.tsx, src/components/home-banner.tsx, src/components/home-staking/home-staking.tsx, src/components/link-preview-square.tsx, src/components/modals/cloud-verification.tsx, src/components/modals/modal-wrapper.tsx, src/components/settings-account-detail/settings-account-detail.tsx, src/components/site-icon-preview.tsx, src/components/staking-info/staking-info.tsx, src/components/wallet-card.tsx, src/event-actions/on-app-logged-in.ts, src/event-actions/on-banner-action.ts, src/event-actions/on-banner-add-claim-code.ts, src/event-actions/on-banner-analytics-create.ts, src/event-actions/on-banner-notification-create.ts, src/helpers/get-min-staking-reward-amount.tsx, src/helpers/prefetch-browser-link-icons.ts, src/helpers/web3-browser-utils.ts, src/hooks/use-staking-reward.ts, src/models/banner.ts, src/screens/banners.tsx, src/screens/settings-test.tsx, src/screens/staking-info.tsx, src/services/balance.ts, src/services/remote-config/remote-config-types.ts, src/types.ts, src/utils.ts, src/widgets/staking-widget/index.tsx, src/widgets/staking-widget/staking-widget.tsx
=> fix: layout bugs

e2e/5_wallet_reset.test.ts, e2e/helpers/createWallet.ts, e2e/helpers/restoreWallet.ts, package.json, src/components/modals/pin.tsx, src/components/restore-password.tsx, yarn.lock
Fixes #
- HQM-161
- Update Detox
=> feat: HQM-161 Reset Wallet Test

src/components/json-rpc-sign-info.tsx, src/components/json-rpc-sign.tsx, src/components/json-rpc-transaction-info.tsx, src/components/locked-tokens.tsx, src/components/modals/not-enough-gas.tsx, src/contexts/app.ts, src/event-actions/on-earn-get-ticket.ts, src/helpers/await-for-json-rpc-sign.ts, src/i18n.ts, src/screens/json-rpc-sign-screen.tsx, src/screens/settings-test.tsx, src/services/__tests__/balance.test.ts, src/services/balance.ts, src/services/eth-sign.ts, src/types.ts, src/utils.ts, src/variables/EIP155.ts, src/variables/common.ts
Fixes #
- raffle transactions
- Balance constructor now support BigNumber type
=> feat(Raffle): transactions

scripts/clean-ios-app.sh
=> feat: clean-ios-app add physical ios device support

src/contexts/app.ts, src/debug-vars.ts, src/event-actions/on-staking-rewards.ts, src/helpers/await-for-json-rpc-sign.ts, src/helpers/ledger-transport-wrapper.ts, src/services/cosmos.ts, src/services/eth-sign.ts, src/services/logger.ts, src/types.ts
Fixes #
- get staking rewards transactions popup
=> feat(StakingRewards): transactions

ios/haqq.xcodeproj/project.pbxproj, src/components/wallet-card.tsx, src/variables/common.ts
Fixes #
- Update card layout
-
-
=> style(HQM-172): Add action button to card

.github/workflows/e2e.yml
=> feat: new e2e action

.github/workflows/e2e.yml
=> feat: e2e.yml

package.json, src/components/ledger-accounts/ledger-accounts.tsx, src/screens/ledger-accounts.tsx
=> feat: ledger choose account

src/components/staking-validators/staking-validators.tsx, src/screens/staking-validators.tsx
=> fix: crash

src/screens/web3-browser.tsx, src/services/json-rpc-middleware/json-rpc-methods-handlers.ts
Fixes #
- web3 browser redirect loop
=> fix: web3 browser redirect loop

src/components/modals/pin.tsx, src/components/modals/qr/qr.tsx, src/components/transaction-address.tsx, src/event-actions/on-deep-link.ts, src/helpers/await-for-json-rpc-sign.ts, src/helpers/await-for-scan-qr.ts, src/helpers/parse-deep-link.ts, src/i18n.ts, src/screens/settings-address-book.tsx, src/screens/settings-test.tsx, src/services/json-rpc-middleware/json-rpc-methods-handlers.ts, src/types.ts, src/utils.ts
=> fix: hqm 187 qr scanner

docs/developer-mode.md, docs/inpage-bridge-web3.md, src/services/json-rpc-middleware/index.ts
Fixes #
-  crash when user reject json rpc request
- docs typo
=> fix: crash when user reject json rpc request

src/widgets/ad-widget/index.tsx
Fixes #
- height of banner widget
=> fix: height of banner widget

src/widgets/raffles.widget/index.tsx
=> feat: hide raffles on empty

src/screens/ledger-accounts.tsx
Fixes #
- ledger path for import account
=> fix: ledger path

src/screens/browser-home-page-screen.tsx, src/screens/settings-developer-tools.tsx, src/variables/common.ts
=> fix: browser icons

__tests__/init.ts, src/models/contracts.ts, src/models/tokens.ts, src/services/balance.ts, src/services/indexer.ts, src/types.ts
=> feat: add tokens store

.github/workflows/distribute-android.yml, .github/workflows/distribute-ios.yml, .github/workflows/distribute.yml, src/components/account-info/account-info-header.tsx, src/components/total-value-info/total-value-info-header.tsx, src/components/wallets/wallets.tsx, src/helpers/is-feature-enabled.ts, src/screens/locked-tokens.tsx, src/screens/wallets.tsx, src/types/env.d.ts
=> feat: enable vesting by default

src/event-actions/on-wallets-balance-check.ts, src/events.ts, src/hooks/use-is-balances-sync.ts
Fixes #
- balances skeleton placeholder
=> fix: balances skeleton placeholder

src/hooks/use-is-balances-sync.ts
=> fix: balance loading

.eslintrc.js, src/components/modals/ledger-locked.tsx, src/helpers/ledger-transport-wrapper.ts, src/helpers/provider-instance.ts, src/screens/home-staking.tsx, src/screens/staking-delegate-form.tsx, src/screens/staking-delegate-preview.tsx, src/screens/staking-undelegate-form.tsx, src/variables/common.ts
=> fix: ledger staking

src/helpers/provider-instance.ts, src/screens/staking-delegate-preview.tsx, src/screens/staking-undelegate-preview.tsx
=> fix: ledger modals

src/debug-vars.ts, src/helpers/await-for-json-rpc-sign.ts, src/helpers/ledger-transport-wrapper.ts, src/screens/settings-developer-tools.tsx, src/services/cosmos.ts, src/utils.ts
Fixes #
- staking ledger reward
=> fix: staking ledger reward

src/models/wallet.ts
=> fix: wallet remove

src/helpers/check-app-version.ts
=> fix: check app version

src/components/in-app-browser.tsx, src/components/web3-browser/web3-browser.tsx, src/services/json-rpc-middleware/json-rpc-methods-handlers.ts
=> fix: browser reload

src/components/popup-header.tsx, src/components/popup/go-back-popup-button.tsx, src/screens/choose-account-screen.tsx, src/screens/signin-restore-wallet.tsx, src/screens/signin-store-wallet.tsx, src/types.ts
=> feat: choose account for sss

src/components/modals/modal-wrapper.tsx, src/components/modals/view-error-details.tsx, src/components/staking-delegate-preview/staking-delegate-preview.tsx, src/components/staking-undelegate-preview/staking-undelegate-preview.tsx, src/components/transaction-confirmation/transaction-confirmation.tsx, src/components/ui/error-text.tsx, src/hooks/use-error.ts, src/i18n.ts, src/screens/settings-test.tsx, src/screens/staking-delegate-preview.tsx, src/screens/staking-undelegate-preview.tsx, src/screens/transaction-confirmation.tsx, src/types.ts
=> feat(HQM-198): Error details modal with copy option

src/screens/home-staking.tsx
Fixes #
- [MaxListenersExceededWarning listeners amount](https://linear.app/haqq/issue/HQM-182/maxlistenersexceededwarning-listeners-amount)
=> fix(HQM-182): Remove circular dependency from staking home screen

src/components/staking-info/staking-info.tsx, src/components/staking-validators/validator-avatar.tsx, src/components/staking-validators/validator-row.tsx
=> feat: delegator avatar

src/models/tokens.ts
=> fix: ISLM token sending

src/helpers/is-feature-enabled.ts
=> feat: enable tokens

src/components/in-app-browser.tsx, src/components/web3-browser/web3-browser.tsx, src/hooks/use-webview-shared-props.tsx
Fixes #
- browser keyboard avoid
=> fix: browser keyboard avoid

src/app.tsx
Fixes #
- staking screens performance
=> fix: staking screens performance

src/components/staking-delegate-form/staking-delegate-form.tsx, src/components/staking-undelegate-form/staking-undelegate-form.tsx, src/screens/staking-delegate-form.tsx, src/screens/staking-undelegate-form.tsx
Fixes #
- Recalculate fee when coins amount changed
-
-
=> fix: staking fee issue

src/screens/choose-account-screen.tsx
=> feat: show total balance on choose account screen

src/components/ui/copy-menu.tsx
=> fix(HQM-207): Fix copy menu bg based on theme

src/screens/browser-home-page-screen.tsx, src/screens/browser-privacy-details-screen.tsx, src/screens/raffle-details.tsx, src/screens/value-selector-screen.tsx, src/screens/web3-browser.tsx
Fixes #
- added useCallback wrapper for useFocusEffect
=> fix: added useCallback wrapper for useFocusEffect

src/components/browser-privacy.tsx, src/components/browser-search-page.tsx, src/components/in-app-browser.tsx, src/components/ui/input.tsx, src/components/web3-browser/web3-browser.tsx, src/helpers/webview-geolocation.ts, src/hooks/use-webview-shared-props.tsx, src/models/variables-string.ts, src/variables/common.ts
Fixes #
-  browser geolocation (improve wathPosition)
-  browser search bar height for android
=> fix: browser geolocation

src/event-actions/on-deep-link.ts, src/helpers/whitelist.ts, src/screens/json-rpc-sign-screen.tsx, src/utils.ts
=> feat: contract whitelist

src/helpers/get-app-info.ts, src/services/push-notifications.ts
Fixes #HQM-212
- send token updates on config request
-
-
=> feat: send token updates on config request

src/models/tokens.ts
=> feat: add erc20 icon support

docs/developer-mode.md, src/helpers/whitelist.ts, src/screens/settings-developer-tools.tsx
Fixes #
-  separate whitelist cache for multiply providers
-  added verify address to developer tools
=> fix: separate whitelist cache for multiply providers

src/components/modals/wallets-bottom-sheet.tsx, src/components/wallet-connect-approval.tsx, src/components/wallet-row-variant-5.tsx, src/components/wallet-row.tsx, src/components/wallet-selector.tsx, src/components/web3-browser/web3-browser-header.tsx, src/helpers/await-for-wallet.ts, src/screens/wallet-connect-approval.tsx, src/services/json-rpc-middleware/json-rpc-methods-handlers.ts, src/types.ts
Fixes #
- HQM-213 show account balance while choice account
<table>
<tr>
<td>
</td>
<td>
</td>
</tr>
</table>
=> feat: HQM-213 show account balance while choice account

docs/developer-mode.md, docs/inpage-bridge-web3.md, src/components/custom-header-webview.tsx, src/components/in-app-browser.tsx, src/components/web3-browser/web3-browser.tsx, src/event-actions/on-provider-changed.ts, src/screens/settings-developer-tools.tsx
Fixes #
-  custom headers webview
-  update docs
-  disable developer mode while provider change
=> feat: custom headers webview

src/components/transaction-address.tsx, src/screens/transaction-address.tsx, src/utils.ts
Fixes #
-  Simplify address validation logic and add support for Haqq addresses.
=> feat: bench32 address support for transactionAddress screen

src/components/web3-browser/web3-browser-action-menu.tsx
Fixes #
-  Add safe area insets to action menu
=> fix(Web3Browser): add safe area insets to action menu

src/event-actions/on-deep-link.ts
Fixes #
- refactor  on-deep-link
=> refactor: on-deep-link

src/event-actions/on-deep-link.ts, src/screens/transaction-account.tsx, src/types.ts
Fixes #
-  bench32 qr and deeplink support
=> feat: bench32 qr and deeplink support

android/app/src/debug/AndroidManifest.xml, android/app/src/main/AndroidManifest.xml, package.json, src/screens/settings-test.tsx, yarn.lock
=> feat: add install referrer

src/event-actions/on-track-event.ts, src/helpers/webview-adjust-middleware.ts, src/hooks/use-webview-shared-props.tsx
Fixes #
-  adjust browser middleware
=> feat: adjust browser middleware

src/helpers/whitelist.ts
Fixes #
-  whitelist new url format
`*.domain.com` - allow all sub domains
`https://doman.com` - protocol sensitive (for this example **http**://doman.com is not valid)
`domain.com` - without protocol sensitive
=> feat: whitelist new url format

src/components/popup/dismiss-popup-button.tsx, src/helpers/get-wallet-title.ts, src/screens/news-list.tsx
=> fix: wallet card navigation

src/components/wallet-row-variant-5.tsx
=> fix: wallet row width

src/components/modal-provider.tsx, src/screens/RootStack/index.tsx
=> fix: android modals

src/screens/HomeStack/home.tsx
=> fix: do not hide tab bar on browser tab

src/helpers/explorer-instance.ts
Fixes #
- explorer instance cache
=> feat: explorer instance cache

src/components/proposal-deposit-form/proposal-deposit-form.tsx, src/components/staking-delegate-form/staking-delegate-form.tsx, src/components/transaction-sum/transaction-sum.tsx, src/helpers/get-remote-balance-value.tsx, src/screens/HomeStack/SettingsStack/settings-test.tsx, src/variables/balance.ts, src/variables/common.ts
=> fix: require cycle

src/screens/HomeStack/HomeNewsStack/news-detail.tsx, src/screens/WelcomeStack/index.tsx
=> fix: welcome news details

src/components/staking-delegate-form/staking-delegate-form.tsx, src/components/staking-undelegate-form/staking-undelegate-form.tsx, src/screens/HomeStack/StakingDelegateStack/staking-delegate-form.tsx, src/screens/HomeStack/StakingUndelegateStack/staking-undelegate-form.tsx
Fixes #
[Fix fee calculation and max button](https://linear.app/haqq/issue/HQM-206/fix-fee-calculation-and-max-button)
- Remove toPrecision as unnecessary casting function
- Remove fee from useEffect dependencies
-
=> fix(HQM-206): Fix fee calculations

src/components/token-viewer/token-viewer.tsx, src/helpers/provider-instance.ts, src/screens/HomeStack/SecurityStack/settings-security-pin.tsx, src/screens/WelcomeStack/OnboardingStack/index.tsx, src/screens/WelcomeStack/OnboardingStack/onboarding-repeat-pin.tsx, src/screens/WelcomeStack/SignInStack/index.tsx, src/screens/WelcomeStack/SignInStack/signin-not-exists.tsx, src/screens/choose-account-screen.tsx, src/screens/sss-store-wallet.tsx, src/screens/transaction-select-crypto.tsx, src/services/wallet-connect.ts, src/widgets/tokens-widget/tokens-widget.tsx
Fixes #
- Floating bug with SSS
- Token whitelist
-
=> fix: HQM-221

src/components/modals/qr/qr.tsx, src/services/system-dialog.ts
=> fix: qr code camera

src/components/browser-search-page.tsx
=> fix: HQM-185 backgroundColor on browser-search-page

src/screens/HomeStack/BrowserStack/index.tsx
=> feat: add privacy stack

src/screens/HomeStack/SssMigrate/sss-migrate-store.tsx
=> fix: protection banner

src/helpers/get-provider-storage.ts, src/screens/HomeStack/SssMigrate/sss-migrate-store.tsx
=> fix: sss infinity loading

src/components/staking-validators/validator-avatar.tsx
Fixes #
- Update styles for validator logo
-
-
=> fix(HQM-220): Validator logo

src/event-actions/on-app-initialized.ts, src/event-actions/on-remote-config-sync.ts, src/helpers/get-remote-balance-value.tsx, src/helpers/whitelist.ts, src/hooks/use-remote-config.ts, src/services/remote-config/remote-config-default-values.ts, src/services/remote-config/remote-config-service.ts, src/services/remote-config/remote-config-types.ts, src/services/version.ts
Fixes #
-  cache and optional init for RemoteConfig service
=> feat: hqm-29 cache and optional init for RemoteConfig service

src/event-actions/on-wallet-create.ts, src/event-actions/on-wallet-sss-saved.ts
=> fix: HQM-233 wallet protection init status

patches/url-parse+1.5.10.patch
Fixes #
- disable lowercase for url parse
=> fix: disable lowercase for url parse

src/screens/HomeStack/HomeEarnStack/staking-validators.tsx
Fixes #
- Check cache and update only if cache changed
=> perf: Validators list screen performance

src/components/modals/modal-wrapper.tsx, src/components/modals/qr/qr.tsx, src/components/transaction-address.tsx, src/event-actions/on-deep-link.ts, src/helpers/modal.ts, src/helpers/parse-deep-link.ts, src/screens/HomeStack/AddressStack/settings-address-book.tsx, src/screens/modals-screen.tsx
=> fix: qr modal

src/models/wallet.ts
=> fix: mock wallets

src/components/staking-validators/headers/unstacked-header.tsx, src/event-actions/on-wallet-create.ts, src/screens/HomeStack/HomeFeedStack/wallets.tsx, src/screens/HomeStack/NftDetailsStack/index.tsx, src/screens/HomeStack/index.tsx, src/screens/WelcomeStack/SignUpStack/signup-store-wallet.tsx, src/widgets/raffles.widget/index.tsx
=> fix: navigation bugs

src/app.tsx, src/screens/HomeStack/home.tsx
=> fix: sss verification modal

src/screens/WelcomeStack/SignUpStack/signup-store-wallet.tsx
=> fix: sss provider

src/components/news-detail/news-detail.tsx
=> fix: Fix lists markdown layout

fastlane/Fastfile
=> fix: slack version number

src/components/staking-validators/headers/unstacked-header.tsx
=> fix: Fix validators sort dark mode styles

src/helpers/validators-sort.ts
- Sorting by commission should work by ASC
-
-
=> fix: Change sorting by commission

src/components/finish.tsx, src/screens/WelcomeStack/OnboardingStack/onboarding-finish.tsx, src/screens/WelcomeStack/SignInStack/signin-store-wallet.tsx
=> fix: HQM-242 HQM-238

src/screens/WelcomeStack/SignInStack/signin-shares-not-found.tsx, src/screens/WelcomeStack/SignUpStack/signup-network-exists.tsx, src/screens/choose-account-screen.tsx
=> fix: sss navigation

src/helpers/get-provider-for-new-wallet.ts, src/screens/HomeStack/HomeFeedStack/wallets.tsx, src/screens/HomeStack/ManageAccountsStack/settings-view-recovery-phrase.tsx, src/screens/WelcomeStack/SignUpStack/signup-store-wallet.tsx
Fixes #
- fix: set mnemonic provider as a default one
- add: cloud share check when user try to verify mnemonic phrase
=> fix: set mnemonic provider as a default one

src/components/signin-networks/signin-networks.tsx
=> feat: add sss disabled condition on import page

src/components/wallet-card.tsx, src/components/wallets/wallets.tsx, src/screens/HomeStack/HomeFeedStack/wallets.tsx, src/screens/choose-account-screen.tsx
=> fix: 2nd mnemonic bugs

package.json, src/helpers/get-app-info.ts, yarn.lock
Fixes #
- Add ip address into appinfo section
- Doesn't use netinfo package because it can get only wifi ip address
-
=> feat: Get IP address of user's devices

src/screens/HomeStack/SssMigrate/sss-migrate-finish.tsx
=> fix: sss finish navigation

src/components/modals/cloudShareNotFound.tsx, src/screens/HomeStack/BackupStack/backup-create.tsx, src/screens/HomeStack/BackupStack/backup-verify.tsx, src/screens/HomeStack/BackupStack/backup-warning.tsx, src/screens/HomeStack/BackupStack/index.tsx, src/screens/HomeStack/HomeFeedStack/wallets.tsx, src/screens/HomeStack/ManageAccountsStack/settings-account-detail.tsx, src/screens/HomeStack/home.tsx, src/screens/HomeStack/index.tsx, src/screens/popup-backup-notification.tsx, src/screens/popup-backup-sss-notification.tsx, src/screens/wallet-protection.tsx
=> fix: mnemonic backup for sss account

src/components/ui/copy-menu.tsx, src/components/ui/popover.jsx
=> feat: add new Popover renderer

src/components/home-feed.tsx, src/components/transactions/contract.tsx, src/event-actions/on-transactions-load.ts, src/helpers/load-transactions.ts
=> fix: transactions loading

src/widgets/ad-widget/index.tsx
Fixes #
- Show both gradient and bg image
-
-
=> chore: Update ad widget layout

package.json, yarn.lock
Fixes #
- https://github.com/haqq-network/haqq-wallet/security/dependabot/27
-
-
=> fix: CVE-2023-45133

src/components/in-app-browser.tsx, src/components/web3-browser/web3-browser-helper.ts
=> fix: onramper

src/app.tsx
=> fix: wallet migration

src/screens/HomeStack/HomeFeedStack/wallets.tsx
=> fix: rootWallet pointer

src/screens/HomeStack/HomeFeedStack/wallets.tsx
=> fix: getProviderForNewWallet

src/components/signin-networks/signin-networks.tsx, src/screens/HomeStack/HomeFeedStack/home-feed.tsx
=> fix: sss disabled condition at import flow

src/screens/HomeStack/HomeFeedStack/wallets.tsx
=> fix: onPressProtection HQM-255

src/event-actions/on-app-mnemonic-backup.ts, src/event-actions/on-staking-rewards.ts, src/event-actions/on-wallet-mnemonic-check.ts, src/screens/HomeStack/JsonRpcSignPopupStack/index.tsx, src/screens/WelcomeStack/SignInStack/signin-store-wallet.tsx, src/screens/modals-screen.tsx, src/types.ts
Fixes #
- All bugs from @iGroza thread: https://haqqnetwork.slack.com/archives/C03RLCFMNCW/p1701085354720889
-
-
=> fix: latest build bugs

src/components/json-rpc-sign-info.tsx, src/components/web3-browser/web3-browser.tsx, src/utils.ts
Fixes #
- HQM-222 [fixed lost connection to MetaMask RpcProvider](https://github.com/haqq-network/haqq-wallet/commit/d4fc21cb902260804aa0df4402ec6b41ff476baf)
- [improve personal sign message](https://github.com/haqq-network/haqq-wallet/commit/ef8f06b70572bed19bd04c193964091989dd99e6)
=> fix: web3 browser metamask rpc issue

src/components/news-detail/news-detail.tsx
=> fix: Update markdown paragraph calculations

src/screens/HomeStack/SettingsStack/settings-test.tsx
=> fix: modals wrapper

e2e/1_signup.test.ts, e2e/4_settings.test.ts, src/components/settings-account-detail/settings-account-detail.tsx, src/components/ui/icon.tsx, src/components/wallet-protection.tsx, src/i18n.ts, src/screens/HomeStack/HomeFeedStack/wallets.tsx, src/screens/HomeStack/ManageAccountsStack/settings-account-detail.tsx, src/screens/wallet-protection.tsx
=> fix: pharse typo

src/components/wallets/wallets.tsx
=> fix: isSecondMnemonic condition

src/components/wallet-card.tsx, src/components/wallets/wallets.tsx, src/models/wallet.ts
=> feat: add isImported flag persistor

src/components/backup-verify/backup-verify.tsx, src/components/wallets/carousel-item.tsx, src/i18n.ts
=> feat: add 24 words mnemonic support

src/hooks/use-webview-shared-props.tsx
Fixes #
-  service and workers
=> feat(WebView): service and workers

src/types.ts, src/widgets/ad-widget/index.tsx, src/widgets/banner-widget/index.tsx
=> feat: add adjust event support in ad/banner

src/screens/HomeStack/BackupStack/backup-verify.tsx
=> fix: mnemonicSaved flag

src/widgets/ad-widget/index.tsx, src/widgets/banner-widget/index.tsx
=> fix: send adjust event in onPress
